import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Investors", description: "A factual overview of Crabionics, its production problem, development work and validation pathway." };

const points = [
  ["The problem", "Mud-crab production brings together a difficult control and repeatability problem across habitat, water conditions, handling and operator decisions."],
  ["The approach", "Crabionics is building a connected system of habitat, observation, local intervention and operating records around that production work."],
  ["The evidence path", "Engineering integration, biological learning and commercial demand are treated as separate questions with separate evidence."],
  ["The company stage", "The current work is focused on integrating the system and defining the validation settings needed to learn what it can support."],
];

export default function InvestorsPage() {
  return <div className="bg-white text-slate-900"><section className="bg-[#102C5C] py-24 text-white lg:py-32"><div className="container-shell max-w-5xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#65c7e8]">Company / Investors</p><h1 className="mt-4 text-5xl font-semibold leading-tight tracking-[-0.04em] text-white sm:text-6xl">A factual view of the problem, the system and the work still ahead.</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-slate-200">The public investment context is the production problem, the operating approach, the institutional relationships and the validation pathway. It is not a claim of completed biological or commercial outcomes.</p></div></section><section className="py-20 lg:py-24"><div className="container-shell grid gap-5 md:grid-cols-2">{points.map(([title,text])=><article key={title} className="rounded-3xl border border-slate-200 bg-white p-8 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><h2 className="text-2xl font-semibold text-[#102C5C]">{title}</h2><p className="mt-4 text-sm leading-7 text-slate-600">{text}</p></article>)}</div></section><section className="border-y border-slate-200 bg-[#f8fafc] py-20"><div className="container-shell"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#168bb8]">Public boundary</p><h2 className="mt-3 text-3xl font-semibold text-[#102C5C] sm:text-4xl">The architecture still needs production evidence.</h2><p className="mt-4 text-slate-600">Institutional relationships support the company’s R&amp;D context. They are not presented as proof of biological performance, economic repeatability or commercial adoption.</p></div><div className="mt-9 flex flex-wrap gap-3"><Link href="/validation" className="rounded-full bg-[#102C5C] px-6 py-3 text-sm font-semibold text-white">See validation</Link><Link href="/company" className="rounded-full border border-slate-300 px-6 py-3 text-sm font-semibold text-[#102C5C]">Company context</Link></div></div></section><section className="py-20"><div className="container-shell flex flex-col justify-between gap-6 rounded-3xl border border-slate-200 bg-[#f8fafc] p-8 md:flex-row md:items-center md:p-10"><div><h2 className="text-3xl font-semibold text-[#102C5C]">For a current company conversation</h2><p className="mt-3 text-slate-600">Contact the team for the latest development and validation context.</p></div><Link href="/contact" className="rounded-full bg-[#102C5C] px-6 py-3 text-sm font-semibold text-white">Talk to us</Link></div></section></div>;
}
