import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Investors", description: "Crabionics company, architecture, institutional relationships and validation pathway." };

const points = [["Opportunity", "Mud-crab production is a high-value category with a difficult control and repeatability problem."], ["Architecture", "Crabionics is building an integrated system spanning physical habitat, sensing, edge control and operating software."], ["Validation", "The company is separating engineering integration from biological and commercial validation."], ["Thesis", "The long-term business thesis is to turn production learning into infrastructure and operating capability, subject to validation."]];

export default function InvestorsPage() {
  return <div className="bg-white text-slate-900"><section className="bg-[#102C5C] py-24 text-white lg:py-32"><div className="container-shell max-w-5xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#65c7e8]">Company / Investors</p><h1 className="mt-4 text-5xl font-semibold leading-tight tracking-[-0.04em] text-white sm:text-6xl">Building the infrastructure for more controlled mud-crab production.</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-slate-200">Crabionics is at the transition from technology integration toward controlled validation. The public investment story is the architecture, the problem, the validation pathway and the institutional context.</p></div></section><section className="py-20 lg:py-24"><div className="container-shell grid gap-5 md:grid-cols-2">{points.map(([title,text])=><article key={title} className="rounded-3xl border border-slate-200 bg-white p-8 shadow-sm"><h2 className="text-2xl font-semibold text-[#102C5C]">{title}</h2><p className="mt-4 text-sm leading-7 text-slate-600">{text}</p></article>)}</div></section><section className="border-y border-slate-200 bg-[#f8fafc] py-20"><div className="container-shell"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#168bb8]">Current public boundary</p><h2 className="mt-3 text-3xl font-semibold text-[#102C5C] sm:text-4xl">No commercial outcome is implied by the architecture alone.</h2><p className="mt-4 text-slate-600">Biological performance, economic repeatability and commercial adoption require separate evidence. Institutional relationships support the company’s R&amp;D context; they are not presented as proof of production outcomes.</p></div><div className="mt-9 flex flex-wrap gap-3"><Link href="/validation" className="rounded-full bg-[#102C5C] px-6 py-3 text-sm font-semibold text-white">See validation</Link><Link href="/company" className="rounded-full border border-slate-300 px-6 py-3 text-sm font-semibold text-[#102C5C]">Company context</Link></div></div></section><section className="py-20"><div className="container-shell flex flex-col justify-between gap-6 md:flex-row md:items-center"><div><h2 className="text-3xl font-semibold text-[#102C5C]">For serious investor conversations</h2><p className="mt-3 text-slate-600">Contact the team for current company and validation information.</p></div><Link href="/contact" className="rounded-full bg-[#102C5C] px-6 py-3 text-sm font-semibold text-white">Talk to us</Link></div></section></div>;
}
