import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Talk to us", description: "Discuss a mud-crab pilot, technical brief or research partnership with Crabionics." };

const paths = [["Discuss a mud-crab pilot", "For producers and operating partners exploring a defined production conversation.", "Producer"], ["Discuss a technical question", "For technical visitors who want to understand the architecture and integration work.", "Technology partner"], ["Explore a research or technology partnership", "For researchers, institutions and technology partners working on validation.", "Researcher / partner"]];

export default function ContactPage() {
  return <div className="bg-white text-slate-900"><section className="bg-[#f5f8fb] py-24 lg:py-32"><div className="container-shell max-w-5xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#168bb8]">Talk to us</p><h1 className="mt-4 text-5xl font-semibold tracking-[-0.04em] text-[#102C5C] sm:text-6xl">Start with the production question.</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-slate-600">Crabionics is open to conversations with producers, research and pilot partners, processors, technology partners and investors.</p><a href="mailto:sameer@crabionics.com" className="mt-9 inline-flex rounded-full bg-[#102C5C] px-6 py-3 text-sm font-semibold text-white">sameer@crabionics.com</a></div></section>

    <section className="py-20 lg:py-28"><div className="container-shell"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#168bb8]">Choose a conversation</p><h2 className="mt-3 text-4xl font-semibold text-[#102C5C] sm:text-5xl">Three practical ways to engage.</h2></div><div className="mt-12 grid gap-5 lg:grid-cols-3">{paths.map(([title,description,category])=><a key={title} href={`mailto:sameer@crabionics.com?subject=${encodeURIComponent(title)}`} className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm transition hover:-translate-y-0.5 hover:border-[#8bcfe4]"><span className="rounded-full bg-[#effafd] px-3 py-1 text-[11px] font-semibold uppercase tracking-[0.12em] text-[#176d85]">{category}</span><h3 className="mt-6 text-2xl font-semibold text-[#102C5C]">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{description}</p><span className="mt-6 inline-flex text-sm font-semibold text-[#168bb8]">Start an email →</span></a>)}</div></div></section>

    <section className="bg-[#102C5C] py-20 text-white"><div className="container-shell grid gap-10 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#65c7e8]">Useful context</p><h2 className="mt-3 text-4xl font-semibold text-white">Tell us what you are trying to produce or validate.</h2></div><div><p className="text-lg leading-8 text-slate-200">A useful first message can include your name, organisation, role, country or operating region, engagement type and what you would like to discuss. There is no long procurement form.</p><p className="mt-6 text-sm leading-7 text-slate-300">Site requirements, equipment responsibilities, pilot duration and partner outputs are discussed directly and are not published here until confirmed.</p><Link href="/validation" className="mt-7 inline-flex rounded-full bg-white px-6 py-3 text-sm font-semibold text-[#102C5C]">Understand the validation programme</Link></div></div></section></div>;
}
