import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Validation", description: "How Crabionics is validating technology, biology, economics and commercial demand." };

const tracks = [["BIRAC / IHMS","Funded R&D","Execute the approved intelligent hatchery and production-intelligence programme."],["Pond","Biology","Generate field evidence on cohort performance, survival, growth and operating conditions."],["600-box","Controlled finishing","Test repeatable finishing operations, actual costs, yield and production economics."],["Commercial","Demand","Build evidence with processors, buyers and deployment partners."]];

export default function ValidationPage() {
  return <div className="bg-white text-slate-900">
    <section className="bg-[#102C5C] py-24 text-white lg:py-32"><div className="container-shell max-w-5xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#65c7e8]">Validation</p><h1 className="mt-4 text-5xl font-semibold tracking-[-0.04em] text-white sm:text-6xl">From prototype to repeatable production.</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-slate-200">The current programme runs several tracks in parallel because each one answers a different question. The goal is not to prove everything at once. It is to replace assumptions with production evidence.</p></div></section>
    <section className="py-20 lg:py-28"><div className="container-shell"><div className="grid gap-6 md:grid-cols-2">{tracks.map(([title,label,text],index)=><article key={title} className="rounded-2xl border border-slate-200 bg-white p-8 shadow-sm"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#168bb8]">0{index+1} · {label}</p><h2 className="mt-4 text-2xl font-semibold text-[#102C5C]">{title}</h2><p className="mt-4 text-sm leading-7 text-slate-600">{text}</p></article>)}</div></div></section>
    <section className="bg-[#f5f8fb] py-20 lg:py-28"><div className="container-shell"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#168bb8]">What we measure</p><h2 className="mt-3 text-4xl font-semibold text-[#102C5C]">Production evidence, not presentation metrics.</h2></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{["Survival","Growth and harvest weight","Molt events","Water quality","Feed and labour","Energy and operating cost","Interventions and outcomes","Cycle repeatability","Buyer / processor response"].map((item)=><div key={item} className="rounded-xl bg-white p-5 text-sm font-medium text-slate-700 shadow-sm">{item}</div>)}</div></div></section>
    <section className="py-20"><div className="container-shell grid gap-8 lg:grid-cols-[1fr_auto] lg:items-center"><div><h2 className="text-3xl font-semibold text-[#102C5C]">The next gate is evidence from controlled production.</h2><p className="mt-3 max-w-2xl text-slate-600">As the pilot runs, the website will be updated with substantiated results rather than projections.</p></div><Link href="/investors" className="rounded-full bg-[#102C5C] px-6 py-3 text-sm font-semibold text-white">Investor overview</Link></div></section>
  </div>;
}
