import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Validation", description: "The production settings, questions and evidence tracks Crabionics is using to learn what the system can support." , alternates: { canonical: "/validation" } };

const tracks = [
  ["01", "Funded research / IHMS", "System integration", "Defined research setting", "Can the physical setting, observations and operating routines work together as intended?", "Integration records and operating evidence", "The next step is defined by the supported research work and its measurements."],
  ["02", "Pond biology", "Field biological learning", "Pond production context", "What can be learned about cohort performance, survival, growth and operating conditions in a pond setting?", "Cohort, survival, growth and operating observations", "The next step is defined with the relevant field activity and the evidence it produces."],
  ["03", "Controlled finishing", "600-box pilot", "Defined controlled-finishing setting", "Can the controlled-finishing production approach be operated and measured in its intended pilot context?", "Pilot-specific biological and operating measures", "The next step is defined with the pilot plan and the evidence it produces."],
  ["04", "Commercial demand", "Partner validation", "Producer, processor and downstream conversations", "What would partners need to adopt the system and its outputs in their own operating context?", "Partner requirements, constraints and adoption questions", "Commercial demand is assessed separately from engineering and biological evidence."],
];

export default function ValidationPage() {
  return <div className="bg-white text-slate-900"><section className="relative overflow-hidden bg-[#102C5C] py-20 text-white lg:py-28"><div className="container-shell grid items-center gap-12 lg:grid-cols-[1.05fr_0.95fr]"><div><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#65c7e8]">Validation programme</p><h1 className="mt-4 text-5xl font-semibold tracking-[-0.04em] text-white sm:text-6xl">Learn what the system can support, one setting at a time.</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-slate-200">Crabionics separates system integration, biological learning and commercial demand because each asks a different question and requires a different kind of evidence.</p></div><div className="relative hidden min-h-[320px] lg:block"><div className="absolute left-10 top-0 h-full border-l border-dashed border-[#65c7e8]/60"></div><div className="absolute left-0 top-2 flex w-72 items-center gap-4 border border-[#ecd78e] bg-[#fffdf4] p-4 text-[#102C5C]"><span className="text-2xl font-semibold text-[#745a0a]">01</span><span className="font-semibold">System integration</span></div><div className="absolute left-16 top-32 flex w-72 items-center gap-4 border border-[#a8dfed] bg-[#effafd] p-4 text-[#102C5C]"><span className="text-2xl font-semibold text-[#176d85]">02</span><span className="font-semibold">Pond biology</span></div><div className="absolute left-32 top-64 flex w-72 items-center gap-4 border border-[#efc5c5] bg-[#fff7f7] p-4 text-[#102C5C]"><span className="text-2xl font-semibold text-[#8c3030]">03</span><span className="font-semibold">Commercial demand</span></div></div></div></section>

    <section className="py-16 lg:py-20"><div className="container-shell"><div className="border-l-4 border-[#168bb8] bg-[#f8fafc] p-7 shadow-[0_16px_40px_rgba(16,44,92,0.07)] sm:p-10"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#168bb8]">How the tracks relate</p><div className="mt-6 grid gap-4 md:grid-cols-3"><div className="rounded-2xl border border-[#ecd78e] bg-[#fffdf4] p-5"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#745a0a]">Engineering</p><h2 className="mt-3 text-xl font-semibold text-[#102C5C]">Can the system be integrated?</h2></div><div className="rounded-2xl border border-[#a8dfed] bg-[#effafd] p-5"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#176d85]">Biology</p><h2 className="mt-3 text-xl font-semibold text-[#102C5C]">What happens in a defined setting?</h2></div><div className="rounded-2xl border border-[#efc5c5] bg-[#fff7f7] p-5"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#8c3030]">Commercial</p><h2 className="mt-3 text-xl font-semibold text-[#102C5C]">What would partners adopt?</h2></div></div><p className="mt-7 border-t border-slate-200 pt-6 text-sm leading-7 text-slate-600">These tracks are related but distinct. A result in one track does not automatically answer the question in another.</p></div></div></section>

    <section className="border-y border-slate-200 bg-[#f8fafc] py-16 lg:py-20"><div className="container-shell"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#168bb8]">Public validation tracks</p><h2 className="mt-3 text-4xl font-semibold text-[#102C5C] sm:text-5xl">Production setting, question, measurement, next gate.</h2></div><div className="mt-12 grid gap-5 md:grid-cols-2">{tracks.map(([number,title,label,setting,question,measurement,nextGate])=><article key={title} className="rounded-none border border-slate-200 border-t-4 border-t-[#168bb8] bg-white p-7 shadow-[0_18px_50px_rgba(16,44,92,0.07)] transition hover:-translate-y-1 hover:shadow-[0_24px_60px_rgba(16,44,92,0.12)]"><div className="flex items-center justify-between gap-4"><span className="text-xs font-semibold uppercase tracking-[0.16em] text-[#168bb8]">{number}</span><span className="rounded-full bg-slate-100 px-3 py-1 text-[11px] font-semibold uppercase tracking-[0.12em] text-slate-600">{label}</span></div><h2 className="mt-6 text-2xl font-semibold text-[#102C5C]">{title}</h2><dl className="mt-5 space-y-4 text-sm leading-6"><div><dt className="font-semibold text-slate-800">Setting</dt><dd className="text-slate-600">{setting}</dd></div><div><dt className="font-semibold text-slate-800">Question</dt><dd className="text-slate-600">{question}</dd></div><div><dt className="font-semibold text-slate-800">Main measurement</dt><dd className="text-slate-600">{measurement}</dd></div></dl><p className="mt-5 border-t border-slate-100 pt-4 text-xs leading-6 text-slate-500"><strong className="font-semibold text-slate-700">Next gate:</strong> {nextGate}</p></article>)}</div></div></section>

    <section className="py-14"><div className="container-shell"><div className="border-l-4 border-[#65c7e8] bg-[#102C5C] p-8 shadow-[0_18px_50px_rgba(16,44,92,0.14)] sm:p-10"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#65c7e8]">Evidence boundary</p><p className="mt-4 max-w-4xl text-xl font-medium leading-8 text-white">BIRAC/IHMS milestone completion shows progress in putting the system together. Biological, economic and commercial outcomes are learned separately in their own settings.</p></div><div className="mt-10 flex flex-col justify-between gap-6 md:flex-row md:items-center"><div><h2 className="text-3xl font-semibold text-[#102C5C]">Have a validation or pilot question?</h2><p className="mt-3 text-slate-600">Start with the setting, the question and what you need to learn.</p></div><Link href="/contact" className="rounded-full bg-[#102C5C] px-6 py-3 text-sm font-semibold text-white">Explore a partnership</Link></div></div></section></div>;
}
