import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Validation", description: "How Crabionics is separating engineering integration, biological validation and commercial validation." };

const tracks = [
  ["01", "Funded R&D / IHMS", "Engineering integration", "Complete the supported R&D work and integrate the relevant physical, sensing and operating elements.", "Current phase: [NEEDS INPUT]. Main measurement: [NEEDS INPUT]. Next step: [NEEDS INPUT]."],
  ["02", "Pond biology", "Field biological learning", "Generate field learning about cohort performance, survival, growth and operating conditions in a pond context.", "Current phase: [NEEDS INPUT]. Main measurement: [NEEDS INPUT]. Next step: [NEEDS INPUT]."],
  ["03", "Controlled finishing — 600-box pilot", "Controlled biological validation", "Test the controlled-finishing production architecture in its defined pilot setting.", "Current phase: [NEEDS INPUT]. Main measurement: [NEEDS INPUT]. Next step: [NEEDS INPUT]."],
  ["04", "Commercial demand", "Commercial validation", "Understand whether producers, processors and other partners can adopt the system and its outputs.", "Current phase: [NEEDS INPUT]. Main measurement: [NEEDS INPUT]. Next step: [NEEDS INPUT]."],
];

export default function ValidationPage() {
  return <div className="bg-white text-slate-900"><section className="bg-[#102C5C] py-24 text-white lg:py-32"><div className="container-shell max-w-5xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#65c7e8]">Validation</p><h1 className="mt-4 text-5xl font-semibold tracking-[-0.04em] text-white sm:text-6xl">Where the system is today, and what still needs evidence.</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-slate-200">Crabionics is separating engineering integration, biological validation and commercial validation. Each requires its own setting, question and evidence.</p></div></section>

    <section className="py-20 lg:py-24"><div className="container-shell"><div className="rounded-3xl border border-slate-200 bg-[#f8fafc] p-7 sm:p-10"><div className="grid gap-4 text-center sm:grid-cols-5 sm:items-center"><div className="rounded-2xl border border-[#ecd78e] bg-[#fffdf4] p-5"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#745a0a]">Engineering integration</p></div><span className="text-2xl text-[#168bb8]">↓</span><div className="rounded-2xl border border-[#a8dfed] bg-[#effafd] p-5"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#176d85]">Biological validation</p></div><span className="text-2xl text-[#168bb8]">↓</span><div className="rounded-2xl border border-[#efc5c5] bg-[#fff7f7] p-5"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#8c3030]">Commercial validation → scale / repeatability</p></div></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><div className="rounded-2xl bg-white p-5 text-center text-sm font-medium text-slate-700 shadow-sm">Pond biology — field learning track</div><div className="rounded-2xl bg-white p-5 text-center text-sm font-medium text-slate-700 shadow-sm">600-box controlled finishing — defined downstream company validation track</div></div></div></div></section>

    <section className="border-y border-slate-200 bg-[#f8fafc] py-20"><div className="container-shell"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#168bb8]">Public validation tracks</p><h2 className="mt-3 text-4xl font-semibold text-[#102C5C] sm:text-5xl">Related work, distinct questions.</h2><p className="mt-5 text-lg leading-8 text-slate-600">Pond biology and the 600-box pilot are related but distinct biological validation tracks. The public site does not present pond work as a mandatory step before the controlled-finishing pilot.</p></div><div className="mt-12 grid gap-5 md:grid-cols-2">{tracks.map(([number,title,label,question,status])=><article key={title} className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm"><div className="flex items-center justify-between gap-4"><span className="text-xs font-semibold uppercase tracking-[0.16em] text-[#168bb8]">{number}</span><span className="rounded-full bg-slate-100 px-3 py-1 text-[11px] font-semibold uppercase tracking-[0.12em] text-slate-600">{label}</span></div><h2 className="mt-6 text-2xl font-semibold text-[#102C5C]">{title}</h2><p className="mt-4 text-sm leading-7 text-slate-600">{question}</p><p className="mt-5 border-t border-slate-100 pt-4 text-xs leading-6 text-slate-500">{status}</p></article>)}</div></div></section>

    <section className="py-20"><div className="container-shell"><div className="rounded-3xl bg-[#102C5C] p-8 sm:p-10"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#65c7e8]">Important boundary</p><p className="mt-4 max-w-4xl text-xl font-medium leading-8 text-white">BIRAC/IHMS milestone completion demonstrates engineering integration. It does not by itself demonstrate biological, economic or commercial outcomes. Those are validated separately, at later stages, with their own evidence.</p></div><div className="mt-10 flex flex-col justify-between gap-6 md:flex-row md:items-center"><div><h2 className="text-3xl font-semibold text-[#102C5C]">Have a validation or pilot question?</h2><p className="mt-3 text-slate-600">Crabionics is open to conversations with research, production and technology partners.</p></div><Link href="/contact" className="rounded-full bg-[#102C5C] px-6 py-3 text-sm font-semibold text-white">Explore a partnership</Link></div></div></section></div>;
}
