"use client";

import React, { useState } from "react";
import styles from "./control-tower-v3.module.css";
import visualStyles from "./control-tower-visual-v3-2.module.css";

type Tone = "neutral" | "good" | "warn" | "risk";
export type TowerIssue = { number: number; title: string; state: string; labels: string[]; url: string; updated_at?: string };
export type TowerData = { live:boolean; githubLive:boolean; pmoState:string|null; pmoYaml:string|null; pmoStateUrl:string; pmoYamlUrl:string; strategic:string; funding:string; execution:string; validation:string; technology:string; issues:TowerIssue[]; blockers:TowerIssue[]; stale:TowerIssue[]; recentlyUpdated:TowerIssue[]; repoIssues:Record<string,TowerIssue[]> };

function Badge({children,tone="neutral",filled=false}:{children:React.ReactNode;tone?:Tone;filled?:boolean}){return <span className={`${styles.badge} ${tone==="good"?styles.good:tone==="warn"?styles.warn:tone==="risk"?styles.risk:""} ${filled?visualStyles.badgeFilled:""}`}>{children}</span>}
function Card({children,soft=false,accent,priority=false}:{children:React.ReactNode;soft?:boolean;accent?:Tone;priority?:boolean}){return <div className={`${styles.card} ${soft?styles.cardSoft:""} ${accent?styles[`accent${accent[0].toUpperCase()+accent.slice(1)}`]:""} ${priority?visualStyles.cardPriority:""}`}>{children}</div>}
function Section({eyebrow,title,right,children,id}:{eyebrow:string;title:string;right?:React.ReactNode;children:React.ReactNode;id?:string}){return <section id={id} className={styles.section}><div className={styles.sectionHead}><div><div className={styles.eyebrow}>{eyebrow}</div><h2 className={styles.sectionTitle}>{title}</h2></div>{right}</div>{children}</section>}
function ageDays(v?:string){return v?Math.floor((Date.now()-new Date(v).getTime())/86400000):null}

function SubsystemIcon({name}:{name:string}){
 const common={viewBox:"0 0 32 32",fill:"none",xmlns:"http://www.w3.org/2000/svg",ariaHidden:true as const};
 if(name==="Habitat") return <svg {...common}><rect x="5" y="8" width="22" height="16" rx="4" stroke="currentColor" strokeWidth="2"/><path d="M8 19c4-4 12-4 16 0M10 12h12" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/></svg>;
 if(name==="CrabSense") return <svg {...common}><path d="M6 18c3-7 7-7 10 0s7 7 10 0" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/><circle cx="16" cy="12" r="2.5" stroke="currentColor" strokeWidth="2"/><path d="M16 5v3M8 8l2 2M24 8l-2 2" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/></svg>;
 if(name==="AquaOS") return <svg {...common}><rect x="6" y="7" width="20" height="18" rx="4" stroke="currentColor" strokeWidth="2"/><path d="M11 12h10M11 16h6M11 20h10M4 12H2M30 12h-2M4 20H2M30 20h-2" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/></svg>;
 if(name==="CrabPod") return <svg {...common}><rect x="7" y="6" width="18" height="20" rx="3" stroke="currentColor" strokeWidth="2"/><path d="M11 11h10M11 16h6M11 21h10" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/><path d="M25 11l3-2M25 21l3 2" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/></svg>;
 return <svg {...common}><path d="M16 5c5 0 9 4 9 9v5c0 5-4 8-9 8s-9-3-9-8v-5c0-5 4-9 9-9Z" stroke="currentColor" strokeWidth="2"/><path d="M11 14c2-2 8-2 10 0M12 20c2 1 6 1 8 0" stroke="currentColor" strokeWidth="2" strokeLinecap="round"/><circle cx="12" cy="11" r="1" fill="currentColor"/><circle cx="20" cy="11" r="1" fill="currentColor"/></svg>;
}

function inlineMarkdown(text:string){return text.split(/(\\*\\*[^*]+\\*\\*|`[^`]+`)/g).filter(Boolean).map((part,i)=>part.startsWith("**")&&part.endsWith("**")?<strong key={i}>{part.slice(2,-2)}</strong>:part.startsWith("`")&&part.endsWith("`")?<code key={i}>{part.slice(1,-1)}</code>:<React.Fragment key={i}>{part}</React.Fragment>)}
function Markdown({text}:{text:string}){const lines=text.split(/\r?\n/);const blocks:React.ReactNode[]=[];let i=0;while(i<lines.length){const line=lines[i].trim();if(!line){i++;continue}if(/^\|/.test(line)&&i+1<lines.length&&/^\|?\s*:?-{3,}/.test(lines[i+1].replace(/^\|/,""))){const raw:string[]=[];while(i<lines.length&&/^\|/.test(lines[i].trim())){raw.push(lines[i].trim());i++}const rows=raw.filter(x=>!/^\|?\s*:?-{3,}/.test(x.replace(/^\|/,""))).map(x=>x.split("|").slice(1,-1).map(c=>c.trim()));const [head,...body]=rows;blocks.push(<div key={`table-${i}`} className={styles.tableScroll}><table><thead><tr>{(head??[]).map((c,n)=><th key={n}>{inlineMarkdown(c)}</th>)}</tr></thead><tbody>{body.map((r,n)=><tr key={n}>{r.map((c,j)=><td key={j}>{inlineMarkdown(c)}</td>)}</tr>)}</tbody></table></div>);continue}if(/^#{1,3}\s+/.test(line)){blocks.push(<h3 key={i}>{inlineMarkdown(line.replace(/^#{1,3}\s+/,""))}</h3>);i++;continue}if(/^[-*]\s+/.test(line)){const items:string[]=[];while(i<lines.length&&/^[-*]\s+/.test(lines[i].trim())){items.push(lines[i].trim().replace(/^[-*]\s+/,""));i++}blocks.push(<ul key={i}>{items.map((x,n)=><li key={n}>{inlineMarkdown(x)}</li>)}</ul>);continue}const parts=[line];i++;while(i<lines.length&&lines[i].trim()&&!/^[-*]\s+/.test(lines[i].trim())&&!/^#{1,3}\s+/.test(lines[i].trim())&&!/^\|/.test(lines[i].trim())){parts.push(lines[i].trim());i++}blocks.push(<p key={i}>{parts.map((x,n)=><React.Fragment key={n}>{n>0&&" "}{inlineMarkdown(x)}</React.Fragment>)}</p>)}return <div className={styles.markdown}>{blocks}</div>}

function Issues({issues,limit=8}:{issues:TowerIssue[];limit?:number}){return issues.length?<div className={styles.grid2}>{issues.slice(0,limit).map(x=><a key={x.number} href={x.url} target="_blank" rel="noreferrer" className={styles.issue}><div className={styles.issueTitle}>#{x.number} · {x.title}</div><div className={styles.issueMeta}>{x.labels.length?x.labels.join(" · "):"No labels"} · Updated {ageDays(x.updated_at)??"?"}d ago</div></a>)}</div>:<Card soft><div className={styles.cardSub}>No governed open work returned by GitHub.</div></Card>}

const tabs=["programme","readiness","evidence","execution","technology","pmo"] as const;
const maturity:Array<[string,string,Tone]>= [["Software","Core lifecycle implemented","warn"],["Technology","Controlled integration","warn"],["Hardware","Integration pending","warn"],["Biology","Not yet validated","risk"],["Production","Not yet validated","risk"],["Commercial","Early / not yet validated","risk"],["IP","Evidence / reconciliation","warn"],["Corporate","Diligence / reconciliation","warn"],["Funding","Validation capital / funded lane","warn"]];
const roadmap=["Technology integration","Controlled lab validation","Biological validation","600-box production validation","Processor / customer validation","Repeatable commercial production","Scale / repeatability"];
const claimChain=["Claim / requirement","Implementation","Experiment","Raw evidence","Verdict","Economic implication"];
const outcomeChain=["Biological state","AquaOS decision","Intervention / action","Timestamp","Response","Biological outcome","Confidence","Human override"];
const company:Array<[string,string,string,Tone]>= [["Habitat","Production environment","Physical foundation","warn"],["CrabSense","Sense","Telemetry / observations","warn"],["AquaOS","State → Decide","Decision + event layer","good"],["CrabPod","Intervene","Actuator / command execution","warn"],["BioPod","Outcome","Biological response + evidence","risk"]];
const timeline:Array<[string,string,string,Tone]>= [["NOW","Technology integration","AquaOS lifecycle → CrabPod runtime → integrated laboratory proof","warn"],["M0 → M1","BIRAC / IHMS","Release readiness and monitoring/control prototype","warn"],["M1 → M2","Evidence generation","Dashboard, alerting and controlled validation","neutral"],["M2 → M3","Pilot validation","Biological validation, pilot evidence and final deliverables","neutral"],["POST-M3","Company path","600-box → processor/customer → repeatable commercial production","risk"]];
const capital=["Controlled laboratory proof","Engineering evidence","Biological evidence","Production economics","Processor / customer evidence","Repeatable production"];
const riskLadder=["Technology integration","Biological performance","Production repeatability","Unit economics","Processor demand","Commercial scale"];

export default function ControlTowerTabs({data}:{data:TowerData}){
 const [active,setActive]=useState<(typeof tabs)[number]>("programme");
 const status=!data.live?"DEGRADED · PMO STATE UNAVAILABLE":data.githubLive?"LIVE · PMO + GITHUB":"LIVE · PMO ONLY — GITHUB FEED UNAVAILABLE";
 const setTab=(id:(typeof tabs)[number])=>{setActive(id);window.scrollTo({top:0,behavior:"smooth"})};
 return <main className={styles.tower}><div className={styles.inner}>
  <header className={styles.hero}>
   <div className={styles.heroTop}><Badge tone={data.live&&data.githubLive?"good":data.live?"warn":"risk"} filled={data.live&&data.githubLive}>{status}</Badge><div className={styles.source}><div className={styles.sourceLabel}>SOURCE AUTHORITY</div><a className={styles.sourceLink} href={data.pmoStateUrl} target="_blank" rel="noreferrer">PMO → CURRENT_STATE.md</a></div></div>
   <div><div className={styles.eyebrow}>Crabionics programme & evidence system</div><h1 className={styles.heroTitle}>Control Tower</h1><p className={styles.heroCopy}>One governed data model, multiple views. Programme state comes from PMO; implementation truth comes from owning repositories; operational proof comes from evidence.</p></div>
  </header>
  <nav className={styles.tabs} aria-label="Control Tower views">{tabs.map(id=><button key={id} type="button" className={`${styles.tab} ${active===id?styles.tabActive:""}`} onClick={()=>setTab(id)}>{id[0].toUpperCase()+id.slice(1)}</button>)}</nav>

  {active==="programme"&&<div className={styles.tabPanel}>
   <section className={styles.externalHero}><div><div className={styles.eyebrow}>30-second company view</div><h2 className={styles.externalTitle}>Precision production infrastructure + operating software for mud-crab aquaculture.</h2><p className={styles.externalCopy}>Crabionics is proving integrated technology in a controlled laboratory environment before claiming biological or commercial validation.</p></div><Card accent="warn" priority><div className={styles.cardLabel}>CURRENT GATE</div><div className={styles.stageValue}>Technology integration → controlled validation</div><Badge tone="warn" filled>Evidence boundary</Badge></Card></section>
   <section className={styles.commandGrid}>
    <Card accent="warn" priority><div className={styles.commandKicker}>NOW</div><div className={styles.commandTitle}>Prove the integrated technology loop</div><div className={styles.commandFlow}>Sense → State → Decide → Intervene → Outcome</div></Card>
    <Card><div className={styles.commandKicker}>NEXT PROOF</div><div className={styles.commandTitle}>Controlled laboratory evidence</div><div className={styles.commandSub}>Reproducible runtime evidence on the governed integration path.</div></Card>
    <Card accent="risk"><div className={styles.commandKicker}>BIGGEST UNKNOWN</div><div className={styles.commandTitle}>Biological performance</div><div className={styles.commandSub}>No biological claim without measured experimental evidence.</div></Card>
    <Card><div className={styles.commandKicker}>SUPPORT REQUIRED</div><div className={styles.commandTitle}>Technical + biological + programme execution</div><div className={styles.commandSub}>Integration ownership, biological lead, BIRAC M0 → M1 execution.</div></Card>
   </section>
   <nav className={visualStyles.jumpNav} aria-label="Programme sections"><a href="#map">Map</a><a href="#roadmap">Roadmap</a><a href="#uncertainty">Uncertainty</a><a href="#timeline">Timeline</a><a href="#decision">Decision</a><a href="#capital">Capital</a></nav>
   <Section id="map" eyebrow="Bird's-eye company map" title="How the company works" right={<Badge tone="warn">Closed-loop system</Badge>}><Card><div className={styles.companyMap}>{company.map(([name,role,detail,tone],i)=><React.Fragment key={name}><div className={`${styles.mapNode} ${tone==="good"?styles.mapGood:tone==="warn"?styles.mapWarn:styles.mapRisk}`}><div className={visualStyles.mapNodeIcon} aria-hidden="true"><SubsystemIcon name={name}/></div><div className={styles.mapNodeName}>{name}</div><div className={styles.mapNodeRole}>{role}</div><div className={styles.mapNodeDetail}>{detail}</div></div>{i<company.length-1&&<div className={styles.mapArrow}>→</div>}</React.Fragment>)}</div><div className={styles.feedbackLoop}><span>Sense</span><b>→</b><span>State</span><b>→</b><span>Decide</span><b>→</b><span>Intervene</span><b>→</b><span>Outcome</span><b>↺</b><span>Learn / validate</span></div><p className={styles.mapCaption}>The intended product is a biological control system: habitat + sensing + decision software + intervention + measured outcome.</p></Card></Section>
   <Section id="roadmap" eyebrow="Validation roadmap" title="Technology → commercial repeatability" right={<Badge tone="warn">Current gate highlighted</Badge>}><div className={styles.roadmap}>{roadmap.map((x,i)=><div className={`${styles.roadmapStep} ${i===0?styles.roadmapCurrent:""}`} key={x}><div className={styles.roadmapNumber}>{i+1}</div><div className={styles.roadmapTitle}>{x}</div><Badge tone={i===0?"warn":i<5?"neutral":"risk"} filled={i===0}>{i===0?"NOW":i<5?"GATE":"FUTURE"}</Badge></div>)}</div><p className={visualStyles.visualHint}>Evidence sequence: each step answers whether the next proof boundary has been crossed.</p></Section>
   <Section id="uncertainty" eyebrow="Uncertainty map" title="What uncertainty each gate retires"><div className={styles.riskLadder}>{riskLadder.map((x,i)=><div className={`${styles.riskStep} ${i===0?styles.riskCurrent:""}`} key={x}><span>{i+1}</span><div><strong>{x}</strong><small>{i===0?"Current risk boundary":i===1?"Next major uncertainty":"Downstream gate"}</small></div>{i<riskLadder.length-1&&<b>↓</b>}</div>)}</div><p className={visualStyles.visualHint}>This is an interpretation layer, not a second gate system: G0–G6 remains authoritative.</p></Section>
   <Section id="timeline" eyebrow="Programme timeline" title="BIRAC lane + company validation path"><div className={styles.timeline}>{timeline.map(([period,title,detail,tone],i)=><div className={styles.timelineRow} key={period}><div className={styles.timelineRail}><span className={`${styles.timelineDot} ${tone==="warn"?styles.mapWarn:tone==="risk"?styles.mapRisk:""}`}>{i+1}</span>{i<timeline.length-1&&<i/>}</div><div className={styles.timelineContent}><div className={styles.timelineTop}><Badge tone={tone} filled={tone==="warn"&&i===0}>{period}</Badge><strong>{title}</strong></div><div className={styles.timelineDetail}>{detail}</div></div></div>)}</div><p className={visualStyles.visualHint}>Timing view: it shows when the BIRAC lane and company validation path intersect; it is not itself validation evidence.</p></Section>
   <Section id="decision" eyebrow="Decision & support required" title="What a stakeholder can do with this page"><div className={styles.decisionGrid}><Card accent="warn" priority><div className={styles.cardLabel}>CURRENT DECISION</div><div className={styles.cardValue}>Move from architecture/integration into controlled laboratory proof.</div></Card><Card><div className={styles.cardLabel}>EVIDENCE REQUIRED</div><div className={styles.cardValue}>State → decision → intervention → outcome, reconstructable from governed evidence.</div></Card><Card accent="risk"><div className={styles.cardLabel}>DO NOT CLAIM YET</div><div className={styles.cardValue}>Biological performance, 600-box repeatability or commercial validation.</div></Card><Card><div className={styles.cardLabel}>SUPPORT THAT MATTERS</div><div className={styles.cardValue}>Technical integration, biological leadership, BIRAC execution and validation resources.</div></Card></div></Section>
   <Section id="capital" eyebrow="Capital logic" title="Capital → evidence → risk retirement"><Card><div className={styles.capitalFlow}>{capital.map((x,i)=><React.Fragment key={x}><div className={`${styles.capitalStep} ${i===0?styles.capitalCurrent:""}`}><span>{i+1}</span><div>{x}</div></div>{i<capital.length-1&&<div className={styles.capitalArrow}>→</div>}</React.Fragment>)}</div><div className={styles.capitalFooter}><Badge tone="warn">INVESTMENT LOGIC</Badge><span>Validation capital should buy evidence at the next boundary, not simply more features.</span></div></Card><p className={visualStyles.visualHint}>Capital flow explains what the next funding stage is intended to unlock; it is not a duplicate of the validation ladder.</p></Section>
  </div>}

  {active==="readiness"&&<div className={styles.tabPanel}>
   <Section eyebrow="Maturity at a glance" title="Different parts of Crabionics are at different evidence levels" right={<Badge tone="warn">No single company-wide TRL</Badge>}><Card><div className={styles.maturityGrid}>{maturity.map(([name,value,tone])=><div className={styles.maturityRow} key={name}><div className={styles.maturityName}>{name}</div><div className={styles.maturityValue}>{value}</div><Badge tone={tone}>{tone==="warn"?"AMBER":"RED"}</Badge></div>)}</div><p className={styles.cardSub}>A single TRL would hide differences between software, physical integration, biology and commercial readiness. Use subsystem evidence until the system earns a defensible maturity claim.</p></Card></Section>
   <Section eyebrow="Validation ladder" title="Gate status"><div className={styles.gateBoard}>{roadmap.slice(0,6).map((x,i)=><Card key={x} accent={i===0?"warn":i>1?"risk":undefined} priority={i===0}><div className={styles.gateNumber}>{i+1}</div><div className={styles.gateTitle}>{x}</div><Badge tone={i===0?"warn":i===1?"neutral":"risk"} filled={i===0}>{i===0?"ACTIVE":i===1?"NEXT GATE":"NOT CLEARED"}</Badge><div className={styles.gateMeaning}>{["Architecture/control sufficient to execute proof","Controlled lab evidence required","Biological evidence required","600-box production evidence required","Customer/processor evidence required","Repeatable economics and production required"][i]}</div></Card>)}</div></Section>
   <Section eyebrow="Readiness by stakeholder" title="What each reviewer needs to see"><div className={styles.grid4}><Card><div className={styles.cardLabel}>INVESTOR</div><div className={styles.cardSub}>Risk retired → risk remaining → what the next capital tranche buys.</div></Card><Card><div className={styles.cardLabel}>ADVISOR / BIRAC / KIIT-TBI</div><div className={styles.cardSub}>Milestone → evidence boundary → dependency → decision.</div></Card><Card><div className={styles.cardLabel}>TECHNICAL REVIEWER</div><div className={styles.cardSub}>Subsystem maturity → integration gap → acceptance evidence.</div></Card><Card><div className={styles.cardLabel}>PROCESSOR</div><div className={styles.cardSub}>Predictable supply → consistency → traceability → economics.</div></Card></div></Section>
  </div>}

  {active==="evidence"&&<div className={styles.tabPanel}>
   <Section eyebrow="Evidence model" title="Claim → proof, not claim → presentation"><div className={styles.chain}>{claimChain.map((x,i)=><div className={styles.chainStep} key={x}><span>{i+1}</span><div>{x}</div></div>)}</div></Section>
   <Section eyebrow="AquaOS evidence gate" title="State → decision → intervention → outcome" right={<Badge tone="warn">Mandatory for Dataset-001</Badge>}><Card><div className={styles.outcomeChain}>{outcomeChain.map((x,i)=><React.Fragment key={x}><div className={`${styles.outcomeStep} ${i===5?styles.outcomeBiology:""}`}><span>{i+1}</span><strong>{x}</strong></div>{i<outcomeChain.length-1&&<div className={styles.outcomeArrow}>→</div>}</React.Fragment>)}</div><div className={styles.fieldGrid}><div><b>Minimum record</b><span>Biological state · AquaOS decision · intervention/action · timestamp · response · biological outcome</span></div><div><b>Governance</b><span>Confidence · human override · identity/correlation/provenance where applicable</span></div></div></Card></Section>
   <Section eyebrow="Evidence discipline" title="Known / observed / inferred / unknown / needs experiment"><div className={styles.grid5}><Card><Badge tone="good">KNOWN</Badge><div className={styles.cardSub}>Recorded in authoritative PMO/repository state.</div></Card><Card><Badge>OBSERVED</Badge><div className={styles.cardSub}>Directly visible in current issues, commits or evidence.</div></Card><Card><Badge tone="warn">INFERRED</Badge><div className={styles.cardSub}>Interpretation derived from observed facts.</div></Card><Card><Badge tone="risk">UNKNOWN</Badge><div className={styles.cardSub}>Not established by the available source.</div></Card><Card><Badge tone="warn">NEEDS EXPERIMENT</Badge><div className={styles.cardSub}>Requires a defined experiment and evidence artifact.</div></Card></div></Section>
   <Section eyebrow="Evidence boundary" title="Established vs not yet proven"><div className={styles.grid2}><Card accent="good"><Badge tone="good">ESTABLISHED</Badge><div className={styles.cardSub}>Governance foundation; BIRAC execution lane; AquaOS lifecycle; synthetic closed-loop integration; validation architecture.</div></Card><Card accent="risk"><Badge tone="risk">NOT YET PROVEN</Badge><div className={styles.cardSub}>Physical sensor/actuator loop; biological response; repeatable production performance; 600-box economics; processor/customer validation.</div></Card></div></Section>
  </div>}

  {active==="execution"&&<div className={styles.tabPanel}>
   <section className={styles.commandBanner}><div><div className={styles.eyebrow}>Execution command centre</div><h2>Execute the current plan. Use evidence to select the next gate.</h2></div><Badge tone="warn" filled>Current plan wins</Badge></section>
   <Section eyebrow="Immediate work" title="NOW / NEXT / LATER"><div className={styles.grid3}><Card accent="warn" priority><div className={styles.commandKicker}>NOW</div><div className={styles.commandTitle}>BIRAC M0 → M1 + integrated lab proof</div><div className={styles.commandSub}>Release readiness, monitoring/control prototype and governed integration evidence.</div></Card><Card><div className={styles.commandKicker}>NEXT</div><div className={styles.commandTitle}>Controlled validation experiments</div><div className={styles.commandSub}>Run the approved experiment, capture raw evidence and preserve provenance.</div></Card><Card accent="risk"><div className={styles.commandKicker}>LATER</div><div className={styles.commandTitle}>Biology → 600-box → commercial</div><div className={styles.commandSub}>Downstream gates; do not pull them forward without evidence.</div></Card></div></Section>
   <Section eyebrow="Explicit signals only" title="Risk / attention" right={<Badge tone={data.blockers.length?"risk":"good"}>{data.blockers.length?`${data.blockers.length} flagged`:"No explicit P0/blocker labels"}</Badge>}><Issues issues={data.blockers}/>{data.stale.length>0&&<div className={styles.staleNote}><Badge tone="warn">STALE SIGNAL</Badge><span>{data.stale.length} open issues have not reported an update for at least 7 days. Staleness is an observation, not proof of blockage.</span></div>}</Section>
   <Section eyebrow="Observed movement" title="Recent governed work"><Issues issues={data.recentlyUpdated}/></Section>
  </div>}

  {active==="technology"&&<div className={styles.tabPanel}>
   <Section eyebrow="Bird's-eye system" title="Habitat → Sense → Decide → Intervene → Outcome"><Card><div className={styles.companyMap}>{company.map(([name,role,detail,tone],i)=><React.Fragment key={name}><div className={`${styles.mapNode} ${tone==="good"?styles.mapGood:tone==="warn"?styles.mapWarn:styles.mapRisk}`}><div className={visualStyles.mapNodeIcon} aria-hidden="true"><SubsystemIcon name={name}/></div><div className={styles.mapNodeName}>{name}</div><div className={styles.mapNodeRole}>{role}</div><div className={styles.mapNodeDetail}>{detail}</div></div>{i<company.length-1&&<div className={styles.mapArrow}>→</div>}</React.Fragment>)}</div><div className={styles.feedbackLoop}><span>Input / sensor</span><b>→</b><span>Observation</span><b>→</b><span>Event</span><b>→</b><span>Decision</span><b>→</b><span>Action / command</span><b>→</b><span>Acknowledgement / outcome</span></div></Card></Section>
   <Section eyebrow="Architecture doctrine" title="Model-agnostic but biology-specific"><Card accent="warn"><div className={styles.principle}>Models, sensors, controllers and actuators are replaceable infrastructure. The intended control/data moat is the biological ontology, event model, control policies and validated outcomes.</div><p className={styles.cardSub}>This is a governance/architecture principle, not evidence that a moat has already been earned.</p></Card></Section>
   <Section eyebrow="Hardware resilience" title="Modular components + supply-risk control"><div className={styles.grid4}><Card><div className={styles.cardLabel}>INTERFACE</div><div className={styles.cardValue}>Standard abstraction layer</div></Card><Card><div className={styles.cardLabel}>SOURCING</div><div className={styles.cardValue}>Single-source / dual-source tracked</div></Card><Card><div className={styles.cardLabel}>FX / IMPORT</div><div className={styles.cardValue}>Dependency and exposure tracked</div></Card><Card><div className={styles.cardLabel}>REPLACEMENT</div><div className={styles.cardValue}>Criticality + substitute path</div></Card></div></Section>
   <Section eyebrow="Subsystem truth" title="What each layer owns"><div className={styles.stack}>{company.map(([name,role,detail,tone])=><div className={styles.stackRow} key={name}><div className={visualStyles.stackIdentity}><div className={visualStyles.stackIcon}><SubsystemIcon name={name}/></div><div className={styles.stackName}>{name}</div></div><div className={styles.stackRole}>{role}</div><div className={styles.stackStatus}>{detail} · <Badge tone={tone}>{tone==="good"?"implemented layer":tone==="warn"?"integration / evidence pending":"biological proof pending"}</Badge></div></div>)}</div></Section>
  </div>}

  {active==="pmo"&&<div className={styles.tabPanel}>
   <div className={visualStyles.authorityNote}><Badge filled>RAW / AUTHORITATIVE</Badge><span>PMO tab = unfiltered programme source. Execution tab = curated, prioritized operating view.</span></div>
   <Section eyebrow="PMO source" title="Authoritative programme state"><div className={styles.sourceMini}><a href={data.pmoStateUrl} target="_blank" rel="noreferrer">CURRENT_STATE.md</a><a href={data.pmoYamlUrl} target="_blank" rel="noreferrer">PMO YAML</a></div><Card><Markdown text={data.strategic}/></Card></Section>
   <Section eyebrow="Execution posture" title="Current governed plan"><Card><Markdown text={data.execution}/></Card></Section>
   <Section eyebrow="Funding boundary" title="BIRAC execution lane"><Card accent="warn"><Markdown text={data.funding}/></Card></Section>
   <Section eyebrow="Validation" title="Authoritative gate ladder"><Card><Markdown text={data.validation}/></Card></Section>
   <Section eyebrow="Technology" title="Core technology truth"><Card><Markdown text={data.technology}/></Card></Section>
   <Section eyebrow="Raw work feed" title="Open PMO issues" right={<Badge tone={data.githubLive?"good":"warn"}>{data.githubLive?`${Math.min(data.issues.length,8)} shown · ${data.issues.length} open`:"GitHub feed unavailable"}</Badge>}><Issues issues={data.issues} limit={8}/>{data.issues.length>8&&<div className={visualStyles.feedNote}>Showing the 8 most recently updated issues by default. The PMO tab is the raw feed; open GitHub for the complete issue set.</div>}</Section>
  </div>}

  <footer className={styles.footer}><strong>Control rule:</strong> PMO defines company state; owning repositories define implementation truth; runtime/raw evidence defines operational proof. The Control Tower is only a projection. <a href={data.pmoStateUrl} target="_blank" rel="noreferrer">Open PMO boot file</a>.</footer>
 </div></main>
}
