"use client";

import React, { useState } from "react";
import styles from "./control-tower-v3.module.css";

export type TowerIssue = { number: number; title: string; state: string; labels: string[]; url: string; updated_at?: string };
export type TowerData = {
  live: boolean; githubLive: boolean; pmoState: string | null; pmoYaml: string | null; pmoStateUrl: string; pmoYamlUrl: string;
  strategic: string; funding: string; execution: string; validation: string; technology: string;
  issues: TowerIssue[]; blockers: TowerIssue[]; stale: TowerIssue[]; recentlyUpdated: TowerIssue[]; repoIssues: Record<string, TowerIssue[]>;
};

type Tone = "neutral" | "good" | "warn" | "risk";
function Badge({ children, tone = "neutral" }: { children: React.ReactNode; tone?: Tone }) { return <span className={`${styles.badge} ${tone === "good" ? styles.good : tone === "warn" ? styles.warn : tone === "risk" ? styles.risk : ""}`}>{children}</span>; }
function Section({ eyebrow, title, right, children }: { eyebrow: string; title: string; right?: React.ReactNode; children: React.ReactNode }) { return <section className={styles.section}><div className={styles.sectionHead}><div><div className={styles.eyebrow}>{eyebrow}</div><h2 className={styles.sectionTitle}>{title}</h2></div>{right}</div>{children}</section>; }
function Card({ children, soft = false }: { children: React.ReactNode; soft?: boolean }) { return <div className={`${styles.card} ${soft ? styles.cardSoft : ""}`}>{children}</div>; }
function ageDays(updatedAt?: string) { return updatedAt ? Math.floor((Date.now() - new Date(updatedAt).getTime()) / 86400000) : null; }
function inlineMarkdown(text: string): React.ReactNode[] { return text.split(/(\*\*[^*]+\*\*|`[^`]+`)/g).filter(Boolean).map((part, index) => part.startsWith("**") ? <strong key={index}>{part.slice(2, -2)}</strong> : part.startsWith("`") ? <code key={index}>{part.slice(1, -1)}</code> : <React.Fragment key={index}>{part}</React.Fragment>); }
function MarkdownBlock({ text }: { text: string }) {
  const lines = text.split(/\r?\n/); const blocks: React.ReactNode[] = []; let i = 0;
  while (i < lines.length) {
    const line = lines[i].trim(); if (!line) { i += 1; continue; }
    if (line.startsWith("|") && i + 1 < lines.length && /^\|?\s*:?-{3,}/.test(lines[i + 1].replace(/^\|/, ""))) {
      const tableLines: string[] = []; while (i < lines.length && lines[i].trim().startsWith("|")) { tableLines.push(lines[i].trim()); i += 1; }
      const rows = tableLines.filter((row) => !/^\|?\s*:?-{3,}/.test(row.replace(/^\|/, ""))).map((row) => row.split("|").slice(1, -1).map((cell) => cell.trim()));
      blocks.push(<div key={`table-${i}`} className={styles.tableScroll}><table><thead><tr>{(rows[0] ?? []).map((cell, n) => <th key={n}>{inlineMarkdown(cell)}</th>)}</tr></thead><tbody>{rows.slice(1).map((row, r) => <tr key={r}>{row.map((cell, n) => <td key={n}>{inlineMarkdown(cell)}</td>)}</tr>)}</tbody></table></div>); continue;
    }
    if (/^[-*]\s+/.test(line)) { const items: string[] = []; while (i < lines.length && /^[-*]\s+/.test(lines[i].trim())) { items.push(lines[i].trim().replace(/^[-*]\s+/, "")); i += 1; } blocks.push(<ul key={`list-${i}`}>{items.map((item, n) => <li key={n}>{inlineMarkdown(item)}</li>)}</ul>); continue; }
    if (/^#{1,3}\s+/.test(line)) { const title = line.replace(/^#{1,3}\s+/, ""); blocks.push(<h4 key={`h-${i}`}>{inlineMarkdown(title)}</h4>); i += 1; continue; }
    const paragraph = [line]; i += 1; while (i < lines.length && lines[i].trim() && !/^[-*]\s+/.test(lines[i].trim()) && !/^#{1,3}\s+/.test(lines[i].trim()) && !lines[i].trim().startsWith("|")) { paragraph.push(lines[i].trim()); i += 1; }
    blocks.push(<p key={`p-${i}`}>{paragraph.map((part, n) => <React.Fragment key={n}>{n > 0 && " "}{inlineMarkdown(part)}</React.Fragment>)}</p>);
  }
  return <div className={styles.markdown}>{blocks}</div>;
}
function IssueList({ issues, limit = 10 }: { issues: TowerIssue[]; limit?: number }) { return issues.length ? <div className={styles.grid2}>{issues.slice(0, limit).map((issue) => <a key={issue.number} href={issue.url} target="_blank" rel="noreferrer" className={styles.issue}><div className={styles.issueTitle}>#{issue.number} · {issue.title}</div><div className={styles.issueMeta}>{issue.labels.length ? issue.labels.join(" · ") : "No labels"} · Updated {ageDays(issue.updated_at) ?? "?"}d ago</div></a>)}</div> : <Card soft><div className={styles.cardSub}>No governed open work returned by GitHub.</div></Card>; }

const tabs = [["programme", "Programme"], ["readiness", "Readiness"], ["evidence", "Evidence"], ["execution", "Execution"], ["technology", "Technology"], ["pmo", "PMO"]] as const;
const readiness = [["Software", "Core lifecycle implemented", "good"], ["Technology", "Controlled integration", "warn"], ["Hardware", "Integration pending", "warn"], ["Biology", "Not yet validated", "risk"], ["Production", "Not yet validated", "risk"], ["Commercial", "Early validation", "risk"], ["IP", "Evidence / reconciliation", "warn"], ["Corporate", "Diligence / reconciliation", "warn"], ["Funding", "Validation capital", "warn"]] as const;
const roadmap = ["Technology integration", "Controlled lab validation", "Biological validation", "600-box production validation", "Processor / customer validation", "Repeatable commercial production", "Scale"];
const readinessRoadmap = ["Integrated prototype", "Relevant controlled environment", "Biological validation", "Repeatable production", "Commercial repeatability", "Scale-ready system"];
const claimChain = ["Claim / requirement", "Implementation", "Experiment", "Raw evidence", "Verdict", "Economic implication"];
const interventionChain = ["Biological state", "AquaOS decision", "Intervention / action", "Timestamp", "Response", "Biological outcome", "Confidence", "Human override"];
const companyLayers = [["Habitat", "Production environment", "Physical foundation", "warn"], ["CrabSense", "Sense", "Telemetry / observations", "warn"], ["AquaOS", "State → Decide", "Decision + event layer", "good"], ["CrabPod", "Intervene", "Actuator / command execution", "warn"], ["BioPod", "Outcome", "Biological response + evidence", "risk"]] as const;
const capitalSteps = ["Controlled laboratory proof", "Engineering evidence", "Biological evidence", "Production economics", "Processor / customer evidence", "Repeatable production"];
const timeline = [["NOW", "Technology integration", "AOS-008 / AOS-011 → CrabPod runtime → integrated laboratory proof", "warn"], ["M0 → M1", "BIRAC / IHMS", "Release readiness and monitoring/control prototype", "warn"], ["M1 → M2", "Evidence generation", "Dashboard, alerting and controlled validation", "neutral"], ["M2 → M3", "Pilot validation", "Biological validation, pilot evidence and final deliverables", "neutral"], ["POST-M3", "Company scale path", "600-box → processor/customer → repeatable commercial production", "risk"]] as const;

export default function ControlTowerTabs({ data }: { data: TowerData }) {
  const [active, setActive] = useState<(typeof tabs)[number][0]>("programme");
  const topStatus = !data.live ? "DEGRADED · PMO STATE UNAVAILABLE" : data.githubLive ? "LIVE · PMO + GITHUB" : "LIVE · PMO ONLY — GITHUB FEED UNAVAILABLE";
  const repoLabels: Record<string, string> = { aquaos: "AquaOS", crabpod: "CrabPod", habitat: "Habitat", "crabionics-site": "Website" };
  return <main className={styles.tower}><div className={styles.inner}>
    <header className={styles.hero}><div className={styles.heroTop}><Badge tone={data.live && data.githubLive ? "good" : data.live ? "warn" : "risk"}>{topStatus}</Badge><div className={styles.source}><div className={styles.sourceLabel}>SOURCE AUTHORITY</div><a className={styles.sourceLink} href={data.pmoStateUrl} target="_blank" rel="noreferrer">PMO → CURRENT_STATE.md</a></div></div><div><div className={styles.eyebrow}>Crabionics programme & evidence system</div><h1 className={styles.heroTitle}>Control Tower</h1><p className={styles.heroCopy}>One governed data model, multiple views. Programme state comes from PMO; implementation truth comes from owning repositories; operational proof comes from evidence.</p></div></header>
    <nav className={styles.tabs} aria-label="Control Tower views">{tabs.map(([id, label]) => <button key={id} type="button" className={`${styles.tab} ${active === id ? styles.tabActive : ""}`} onClick={() => setActive(id)}>{label}</button>)}</nav>
    {active === "programme" && <div className={styles.tabPanel}>
      <section className={styles.externalHero}><div><div className={styles.eyebrow}>Universal stakeholder view</div><h2 className={styles.externalTitle}>Precision production infrastructure + operating software for mud-crab aquaculture.</h2><p className={styles.externalCopy}>Crabionics is currently proving integrated technology in a controlled laboratory environment before claiming biological or commercial validation.</p></div><div className={styles.stageCard}><div className={styles.cardLabel}>CURRENT STAGE</div><div className={styles.stageValue}>Technology integration → controlled validation</div><Badge tone="warn">Validation stage</Badge></div></section>
      <Section eyebrow="Bird's-eye company map" title="How the company works" right={<Badge tone="warn">Visual system map</Badge>}><Card><div className={styles.companyMap}>{companyLayers.map(([name, role, detail, tone], i) => <React.Fragment key={name}><div className={`${styles.mapNode} ${tone === "good" ? styles.mapGood : tone === "warn" ? styles.mapWarn : styles.mapRisk}`}><div className={styles.mapNodeName}>{name}</div><div className={styles.mapNodeRole}>{role}</div><div className={styles.mapNodeDetail}>{detail}</div></div>{i < companyLayers.length - 1 && <div className={styles.mapArrow} aria-hidden="true">→</div>}</React.Fragment>)}</div><div className={styles.mapFlow}><span>Sense</span><b>→</b><span>State</span><b>→</b><span>Decide</span><b>→</b><span>Intervene</span><b>→</b><span>Outcome</span></div><p className={styles.mapCaption}>The company is one production system: physical habitat + sensing + decision software + intervention + biological evidence.</p></Card></Section>
      <div className={styles.grid4}><Card><div className={styles.cardLabel}>Immediate objective</div><div className={styles.cardValue}>BIRAC M0 → M1 + integrated laboratory proof</div></Card><Card><div className={styles.cardLabel}>Next proof</div><div className={styles.cardValue}>Sense → State → Decide → Intervene → Outcome</div></Card><Card><div className={styles.cardLabel}>600-box</div><div className={styles.cardValue}>Downstream / gated</div></Card><Card><div className={styles.cardLabel}>Current attention</div><div className={styles.cardValue}>{data.blockers.length ? `${data.blockers.length} explicit blocker/P0 signal(s)` : "No explicit P0/blocker labels"}</div></Card></div>
      <Section eyebrow="Maturity at a glance" title="Different parts of Crabionics are at different evidence levels" right={<Badge tone="warn">No single company-wide TRL</Badge>}><Card><div className={styles.maturityGrid}>{readiness.map(([name, value, tone]) => <div className={styles.maturityRow} key={name}><div className={styles.maturityName}>{name}</div><div className={styles.maturityValue}>{value}</div><Badge tone={tone as Tone}>{(tone as Tone) === "good" ? "GREEN" : (tone as Tone) === "warn" ? "AMBER" : "RED"}</Badge></div>)}</div><p className={styles.cardSub}>A single TRL would hide the physical integration, biological and commercial gaps. Keep maturity multidimensional until the whole system earns a defensible maturity claim.</p></Card></Section>
      <Section eyebrow="Validation roadmap" title="Technology → commercial repeatability"><div className={styles.roadmap}>{roadmap.map((x, i) => <div className={`${styles.roadmapStep} ${i === 0 ? styles.roadmapCurrent : ""}`} key={x}><span>{i + 1}</span><div>{x}</div>{i === 0 && <Badge tone="warn">NOW</Badge>}{i > 0 && i < 5 && <Badge>GATE</Badge>}</div>)}</div></Section>
      <Section eyebrow="Programme timeline" title="BIRAC timeline + company validation path"><div className={styles.timeline}>{timeline.map(([period, title, detail, tone], i) => <div className={styles.timelineRow} key={period}><div className={styles.timelineRail}><span className={`${styles.timelineDot} ${tone === "good" ? styles.mapGood : tone === "warn" ? styles.mapWarn : tone === "risk" ? styles.mapRisk : ""}`}>{i + 1}</span>{i < timeline.length - 1 && <i />}</div><div className={styles.timelineContent}><div className={styles.timelineTop}><Badge tone={tone as Tone}>{period}</Badge><strong>{title}</strong></div><div className={styles.timelineDetail}>{detail}</div></div></div>)}</div><p className={styles.timelineNote}>BIRAC M0–M3 is a funded execution lane. The broader company path continues through biological validation, 600-box production validation, processor/customer evidence and repeatable commercial production.</p></Section>
      <Section eyebrow="What capital unlocks" title="Capital → evidence → risk retirement"><Card><div className={styles.capitalFlow}>{capitalSteps.map((x, i) => <React.Fragment key={x}><div className={`${styles.capitalStep} ${i === 0 ? styles.capitalCurrent : ""}`}><span>{i + 1}</span><div>{x}</div></div>{i < capitalSteps.length - 1 && <div className={styles.capitalArrow}>↓</div>}</React.Fragment>)}</div><div className={styles.capitalFooter}><Badge tone="warn">INVESTMENT LOGIC</Badge><span>Validation capital should buy evidence at the next boundary, not simply more features or architecture.</span></div></Card></Section>
      <Section eyebrow="Evidence boundaries" title="What is proven vs what remains"><div className={styles.grid2}><Card><Badge tone="good">ESTABLISHED</Badge><div className={styles.cardSub}>Company and programme governance foundation; BIRAC execution lane; AquaOS operational lifecycle; synthetic closed-loop integration; validation architecture.</div></Card><Card><Badge tone="risk">NOT YET PROVEN</Badge><div className={styles.cardSub}>Physical sensor/actuator loop, biological response, repeatable production performance, 600-box economics and processor/customer validation.</div></Card></div></Section>
      <Section eyebrow="Evidence chain" title="Claim → proof"><div className={styles.roadmap}>{claimChain.map((x, i) => <div className={styles.roadmapStep} key={x}><span>{i + 1}</span><div>{x}</div></div>)}</div></Section>
      <Section eyebrow="Stakeholder lens" title="What this page answers"><div className={styles.grid4}><Card><div className={styles.cardLabel}>Investor</div><div className={styles.cardSub}>What risk has been retired, what remains, and what capital buys next.</div></Card><Card><div className={styles.cardLabel}>Advisor / BIRAC / KIIT-TBI</div><div className={styles.cardSub}>Current milestone, evidence boundary, dependencies and decisions required.</div></Card><Card><div className={styles.cardLabel}>Technical reviewer</div><div className={styles.cardSub}>Subsystem maturity and the physical integration gap.</div></Card><Card><div className={styles.cardLabel}>Processor</div><div className={styles.cardSub}>Path toward predictable supply, size consistency, traceability and economics.</div></Card></div></Section>
    </div>}
    {active === "readiness" && <div className={styles.tabPanel}><Section eyebrow="Readiness matrix" title="Crabionics maturity is multidimensional" right={<Badge tone="warn">No single company-wide TRL claim</Badge>}><Card><p className={styles.readinessNote}>A single TRL number would hide the difference between software maturity, physical integration, biological validation and commercial readiness. Track the dimensions separately until the whole system has earned a defensible maturity level.</p><div className={styles.readinessGrid}>{readiness.map(([name, value, tone]) => <div className={styles.readinessRow} key={name}><div className={styles.readinessName}>{name}</div><div className={styles.readinessValue}>{value}</div><Badge tone={tone as Tone}>{(tone as Tone) === "good" ? "GREEN" : (tone as Tone) === "warn" ? "AMBER" : "RED"}</Badge></div>)}</div></Card></Section><Section eyebrow="Readiness path" title="Evidence progression"><div className={styles.roadmap}>{readinessRoadmap.map((x, i) => <div className={styles.roadmapStep} key={x}><span>{i + 1}</span><div>{x}</div></div>)}</div></Section></div>}
    {active === "evidence" && <div className={styles.tabPanel}><Section eyebrow="Evidence model" title="Known / Observed / Inferred / Unknown / Needs experiment"><div className={styles.grid5}>{[["KNOWN", "Authoritative PMO or repository state", "good"],["OBSERVED", "Directly visible evidence", "neutral"],["INFERRED", "Interpretation from observations", "warn"],["UNKNOWN", "Not established", "risk"],["NEEDS EXPERIMENT", "Requires a defined experiment", "warn"]].map(([a,b,t]) => <Card key={a}><Badge tone={t as Tone}>{a}</Badge><div className={styles.cardSub}>{b}</div></Card>)}</div></Section><Section eyebrow="AquaOS Dataset-001" title="Mandatory intervention → outcome chain" right={<Badge tone="warn">Evidence gate</Badge>}><Card><div className={styles.chain}>{interventionChain.map((x, i) => <div className={styles.chainStep} key={x}><span>{i + 1}</span>{x}</div>)}</div><p className={styles.cardSub}>The chain must be reconstructable with identity, correlation and provenance fields, and tied to a comparator, implementation version, conditions, measured outcome and verdict.</p></Card></Section><Section eyebrow="Evidence chain" title="Claim → proof"><div className={styles.roadmap}>{claimChain.map((x, i) => <div className={styles.roadmapStep} key={x}><span>{i + 1}</span><div>{x}</div></div>)}</div></Section></div>}
    {active === "execution" && <div className={styles.tabPanel}><div className={styles.grid4}><Card><div className={styles.cardLabel}>NOW</div><div className={styles.cardValue}>BIRAC M0 → M1</div></Card><Card><div className={styles.cardLabel}>Technical dependency</div><div className={styles.cardValue}>AOS-008 → AOS-011 → CrabPod runtime</div></Card><Card><div className={styles.cardLabel}>Scientific owner</div><div className={styles.cardValue}>Biological Lead — TBD</div></Card><Card><div className={styles.cardLabel}>Operating model</div><div className={styles.cardValue}>Programme execution + technical workstream</div></Card></div><Section eyebrow="Current execution posture" title="What happens next"><Card><MarkdownBlock text={data.execution} /></Card></Section><Section eyebrow="Validation dependencies" title="What can block the next proof"><Card><MarkdownBlock text={data.validation} /></Card></Section><Section eyebrow="Live work" title="Current governed PMO issues" right={<Badge tone={data.githubLive ? "good" : "warn"}>{data.githubLive ? `${data.issues.length} open PMO issues` : "Issue feed unavailable"}</Badge>}>{data.githubLive ? <IssueList issues={data.issues} /> : <Card soft><div className={styles.cardSub}>PMO state is available, but GitHub issue status could not be verified. Do not interpret this as zero work.</div></Card>}</Section><Section eyebrow="Risk / attention" title="Explicit signals only"><div className={styles.grid2}>{data.blockers.length ? <IssueList issues={data.blockers} limit={8} /> : <Card><Badge tone="good">NO EXPLICIT BLOCKER LABELS</Badge><div className={styles.cardSub}>This does not mean the programme has no unresolved dependencies.</div></Card>}{data.stale.length ? <Card><Badge tone="warn">STALE SIGNAL</Badge><div className={styles.cardSub}>{data.stale.length} open issues have not reported an update for at least 7 days. Staleness is an observation, not proof of blockage.</div></Card> : null}</div></Section></div>}
    {active === "technology" && <div className={styles.tabPanel}><Section eyebrow="Technology spine" title="Subsystem roles"><div className={styles.stack}>{[["Habitat", "Physical production environment", "Owns habitat engineering and RAS physical truth."],["CrabSense", "Observation / telemetry", "Owns sensing, observation identity and data capture."],["AquaOS", "Event / state / decision layer", "Owns operational lifecycle, correlation and decisions."],["CrabPod", "Command / actuator execution", "Owns physical intervention and acknowledgement."],["BioPod", "Biological outcome", "Owns biological response and evidence boundary."]].map(([name, role, status]) => <div className={styles.stackRow} key={name}><div className={styles.stackName}>{name}</div><div className={styles.stackRole}>{role}</div><div className={styles.stackStatus}>{status}</div></div>)}</div></Section><Section eyebrow="Core technology truth" title="What the PMO currently says"><Card><MarkdownBlock text={data.technology} /></Card></Section><Section eyebrow="Integration contract" title="Critical dependency"><Card><div className={styles.principle}>AOS-008 → AOS-011 → CrabPod runtime → integrated proof</div><div className={styles.cardSub}>The visual map makes the dependency visible; implementation truth remains in the owning repositories.</div></Card></Section></div>}
    {active === "pmo" && <div className={styles.tabPanel}><Section eyebrow="PMO source" title="Authoritative programme state"><Card><div className={styles.sourceMini}><a href={data.pmoStateUrl} target="_blank" rel="noreferrer">CURRENT_STATE.md</a><a href={data.pmoYamlUrl} target="_blank" rel="noreferrer">PMO YAML</a></div><MarkdownBlock text={data.strategic} /></Card></Section><Section eyebrow="Funding boundary" title="PMO funding posture"><Card><MarkdownBlock text={data.funding} /></Card></Section><Section eyebrow="Live execution" title="Current governed PMO work" right={<Badge tone={data.githubLive ? "good" : "warn"}>{data.githubLive ? `${data.issues.length} open PMO issues` : "Issue feed unavailable"}</Badge>}>{data.githubLive ? <IssueList issues={data.issues} /> : <Card soft><div className={styles.cardSub}>Issue feed unavailable. Do not interpret this as zero open work.</div></Card>}</Section><Section eyebrow="Repository view" title="Open work by owning repository"><div className={styles.grid2}>{Object.entries(data.repoIssues).filter(([repo]) => repo !== "crabionics-pmo").map(([repo, issues]) => <Card key={repo}><div className={styles.cardLabel}>{repoLabels[repo] ?? repo}</div><div className={styles.cardValue}>{issues.length} open issue(s)</div>{issues.slice(0,4).map((issue) => <a key={issue.number} href={issue.url} target="_blank" rel="noreferrer" className={styles.issue} style={{marginTop:".6rem"}}><div className={styles.issueTitle}>#{issue.number} · {issue.title}</div></a>)}</Card>)}</div></Section></div>}
    <footer className={styles.footer}><strong>Control rule:</strong> PMO defines company state; owning repositories define implementation truth; runtime/raw evidence defines operational proof. The Control Tower is only a projection. <a href={data.pmoStateUrl} target="_blank" rel="noreferrer">Open PMO boot file</a>.</footer>
  </div></main>;
}
