"use client";

import React, { useMemo, useState } from "react";
import styles from "./control-tower-v3.module.css";
import type { TowerData, TowerIssue } from "./control-tower-tabs";

type Tone = "neutral" | "good" | "warn" | "risk";
type Gate = { id:string; state:string; meaning:string };

const fallbackGates: Gate[] = [
  ["G0", "ACTIVE", "Architecture/control plane sufficient to execute experiments"],
  ["G1", "IMPLEMENTED EARLY / NOT PROGRAMME-VALIDATED", "Synthetic/no-crab integration code exists and has passed repository CI; this is not yet a physical, biological or programme-level validation result"],
  ["G2", "NOT CLEARED", "Biological lab integration evidence required"],
  ["G3", "NOT CLEARED", "Field/pilot readiness evidence required"],
  ["G4", "NOT CLEARED", "600-box biological validation"],
  ["G5", "NOT CLEARED", "Commercial/customer validation"],
  ["G6", "TARGET", "Scale capital / repeatability"],
].map(([id,state,meaning])=>({id,state,meaning}));

function Badge({children,tone="neutral"}:{children:React.ReactNode;tone?:Tone}){return <span className={`${styles.badge} ${tone==="good"?styles.good:tone==="warn"?styles.warn:tone==="risk"?styles.risk:""}`}>{children}</span>}
function Card({children,soft=false,accent}:{children:React.ReactNode;soft?:boolean;accent?:Tone}){return <div className={`${styles.card} ${soft?styles.cardSoft:""} ${accent?styles[`accent${accent[0].toUpperCase()+accent.slice(1)}`]:""}`}>{children}</div>}
function Section({eyebrow,title,right,children}:{eyebrow:string;title:string;right?:React.ReactNode;children:React.ReactNode}){return <section className={styles.section}><div className={styles.sectionHead}><div><div className={styles.eyebrow}>{eyebrow}</div><h2 className={styles.sectionTitle}>{title}</h2></div>{right}</div>{children}</section>}
function ageDays(v?:string){return v?Math.floor((Date.now()-new Date(v).getTime())/86400000):null}
function inlineMarkdown(text:string){return text.split(/(\*\*[^*]+\*\*|`[^`]+`)/g).filter(Boolean).map((part,i)=>part.startsWith("**")&&part.endsWith("**")?<strong key={i}>{part.slice(2,-2)}</strong>:part.startsWith("`")&&part.endsWith("`")?<code key={i}>{part.slice(1,-1)}</code>:<React.Fragment key={i}>{part}</React.Fragment>)}
function Markdown({text}:{text:string}){const lines=text.split(/\r?\n/);const blocks:React.ReactNode[]=[];let i=0;while(i<lines.length){const line=lines[i].trim();if(!line){i++;continue}if(/^\|/.test(line)&&i+1<lines.length&&/^\|?\s*:?-{3,}/.test(lines[i+1].replace(/^\|/,""))){const raw:string[]=[];while(i<lines.length&&/^\|/.test(lines[i].trim())){raw.push(lines[i].trim());i++}const rows=raw.filter(x=>!/^\|?\s*:?-{3,}/.test(x.replace(/^\|/,""))).map(x=>x.split("|").slice(1,-1).map(c=>c.trim()));const [head,...body]=rows;blocks.push(<div key={`table-${i}`} className={styles.tableScroll}><table><thead><tr>{(head??[]).map((c,n)=><th key={n}>{inlineMarkdown(c)}</th>)}</tr></thead><tbody>{body.map((r,n)=><tr key={n}>{r.map((c,j)=><td key={j}>{inlineMarkdown(c)}</td>)}</tr>)}</tbody></table></div>);continue}if(/^#{1,3}\s+/.test(line)){blocks.push(<h3 key={i}>{inlineMarkdown(line.replace(/^#{1,3}\s+/,""))}</h3>);i++;continue}if(/^[-*]\s+/.test(line)){const items:string[]=[];while(i<lines.length&&/^[-*]\s+/.test(lines[i].trim())){items.push(lines[i].trim().replace(/^[-*]\s+/,""));i++}blocks.push(<ul key={i}>{items.map((x,n)=><li key={n}>{inlineMarkdown(x)}</li>)}</ul>);continue}const parts=[line];i++;while(i<lines.length&&lines[i].trim()&&!/^[-*]\s+/.test(lines[i].trim())&&!/^#{1,3}\s+/.test(lines[i].trim())&&!/^\|/.test(lines[i].trim())){parts.push(lines[i].trim());i++}blocks.push(<p key={i}>{parts.map((x,n)=><React.Fragment key={n}>{n>0&&" "}{inlineMarkdown(x)}</React.Fragment>)}</p>)}return <div className={styles.markdown}>{blocks}</div>}
function Issues({issues,limit=8}:{issues:TowerIssue[];limit?:number}){return issues.length?<div className={styles.grid2}>{issues.slice(0,limit).map(x=><a key={x.number} href={x.url} target="_blank" rel="noreferrer" className={styles.issue}><div className={styles.issueTitle}>#{x.number} · {x.title}</div><div className={styles.issueMeta}>{x.labels.length?x.labels.join(" · "):"No labels"} · Updated {ageDays(x.updated_at)??"?"}d ago</div></a>)}</div>:<Card soft><div className={styles.cardSub}>No governed open work returned by GitHub.</div></Card>}
function parseGates(markdown:string|null):Gate[]{if(!markdown)return fallbackGates;const rows=markdown.split(/\r?\n/).map(x=>x.trim()).filter(x=>/^\|\s*G\d\s*\|/.test(x)&&!/^\|\s*Gate\s*\|/i.test(x));const parsed=rows.map(row=>{const cells=row.split("|").slice(1,-1).map(x=>x.trim());return cells.length>=3?{id:cells[0],state:cells[1],meaning:cells[2]}:null}).filter((x):x is Gate=>Boolean(x));return parsed.length===7?parsed:fallbackGates}
function gateTone(g:Gate):Tone{return /ACTIVE|IMPLEMENTED/i.test(g.state)?"good":/TARGET/i.test(g.state)?"neutral":/NOT CLEARED/i.test(g.state)?"risk":"warn"}
function GateCard({gate,onJump}:{gate:Gate;index?:number;onJump:(id:string)=>void}){const tone=gateTone(gate);return <button type="button" onClick={()=>onJump(gate.id)} style={{textAlign:"left",border:"1px solid #dbe5ef",borderRadius:"1rem",background:"#fff",padding:"1rem",cursor:"pointer",boxShadow:"0 7px 22px rgba(15,23,42,.035)"}}><div style={{display:"flex",justifyContent:"space-between",gap:".5rem",alignItems:"center"}}><span style={{fontSize:".68rem",fontWeight:900,color:"#64748b"}}>{gate.id}</span><Badge tone={tone}>{gate.state}</Badge></div><div style={{marginTop:".5rem",color:"#102c5c",fontSize:".92rem",fontWeight:850,lineHeight:1.35}}>{gate.meaning}</div><div style={{marginTop:".55rem",color:"#087f98",fontSize:".68rem",fontWeight:850}}>Open authoritative PMO gate ↗</div></button>}

const tabs=["programme","readiness","evidence","execution","technology","pmo"] as const;
const maturity:Array<[string,string,Tone]>= [["Software","Core lifecycle implemented","good"],["Technology","Controlled integration","warn"],["Hardware","Integration pending","warn"],["Biology","Not yet validated","risk"],["Production","Not yet validated","risk"],["Commercial","Early / not yet validated","risk"],["IP","Evidence / reconciliation","warn"],["Corporate","Diligence / reconciliation","warn"],["Funding","Validation capital / funded lane","warn"]];
const claimChain=["Claim / requirement","Implementation","Experiment","Raw evidence","Verdict","Economic implication"];
const outcomeChain=["Biological state","AquaOS decision","Intervention / action","Timestamp","Response","Biological outcome","Confidence","Human override"];
const company:Array<[string,string,string,Tone]>= [["Habitat","Production environment","Physical foundation","warn"],["CrabSense","Sense","Telemetry / observations","warn"],["AquaOS","State → Decide","Decision + event layer","good"],["CrabPod","Intervene","Actuator / command execution","warn"],["BioPod","Outcome","Biological response + evidence","risk"]];
const timeline:Array<[string,string,string,Tone]>= [["NOW","Technology integration","AquaOS lifecycle → CrabPod runtime → integrated laboratory proof","warn"],["M0 → M1","BIRAC / IHMS","Release readiness and monitoring/control prototype","warn"],["M1 → M2","Evidence generation","Dashboard, alerting and controlled validation","neutral"],["M2 → M3","Pilot validation","Biological validation, pilot evidence and final deliverables","neutral"],["POST-M3","Company path","600-box → processor/customer → repeatable commercial production","risk"]];
const capital=["Controlled laboratory proof","Engineering evidence","Biological evidence","Production economics","Processor / customer evidence","Repeatable production"];
const riskLadder=["Technology integration","Biological performance","Production repeatability","Unit economics","Processor demand","Commercial scale"];

export default function ControlTowerTabsV32({data}:{data:TowerData}){
 const [active,setActive]=useState<(typeof tabs)[number]>("programme");
 const [showAllPmo,setShowAllPmo]=useState(false);
 const status=!data.live?"DEGRADED · PMO STATE UNAVAILABLE":data.githubLive?"LIVE · PMO + GITHUB":"LIVE · PMO ONLY — GITHUB FEED UNAVAILABLE";
 const gates=useMemo(()=>parseGates(data.validation),[data.validation]);
 const scopeRules=useMemo(()=>{const marker="### Scope-control doctrine";const start=data.execution.indexOf(marker);if(start<0)return [];const body=data.execution.slice(start+marker.length);return body.split(/\r?\n/).filter(x=>/^[-*]\s+/.test(x.trim())).map(x=>x.trim().replace(/^[-*]\s+/,""));},[data.execution]);
 const setTab=(id:(typeof tabs)[number])=>{setActive(id);window.scrollTo({top:0,behavior:"smooth"})};
 const jumpGate=(id:string)=>{setActive("pmo");setTimeout(()=>document.getElementById(`gate-${id}`)?.scrollIntoView({behavior:"smooth",block:"center"}),30)};
 return <main className={styles.tower}><div className={styles.inner}>
  <header className={styles.hero}>
   <div className={styles.heroTop}><Badge tone={data.live&&data.githubLive?"good":data.live?"warn":"risk"}>{status}</Badge><div style={{display:"flex",gap:".45rem",flexWrap:"wrap",justifyContent:"flex-end"}}><Badge>AUTHENTICATED VIEW</Badge><div className={styles.source}><div className={styles.sourceLabel}>SOURCE AUTHORITY</div><a className={styles.sourceLink} href={data.pmoStateUrl} target="_blank" rel="noreferrer">PMO → CURRENT_STATE.md</a></div></div></div>
   <div><div className={styles.eyebrow}>Crabionics programme & evidence system</div><h1 className={styles.heroTitle}>Control Tower</h1><p className={styles.heroCopy}>One governed data model, multiple views. Programme state comes from PMO; implementation truth comes from owning repositories; operational proof comes from evidence.</p></div>
  </header>
  <nav className={styles.tabs} aria-label="Control Tower views"><div style={{display:"flex",gap:".25rem",alignItems:"center"}}>{tabs.map((id,i)=><React.Fragment key={id}><button type="button" className={`${styles.tab} ${active===id?styles.tabActive:""}`} onClick={()=>setTab(id)}>{id==="pmo"?"PMO":id[0].toUpperCase()+id.slice(1)}</button>{i<tabs.length-1&&<span aria-hidden style={{color:"#cbd5e1",fontSize:".65rem"}}>›</span>}</React.Fragment>)}</div></nav>
  <div style={{display:"flex",alignItems:"center",gap:".55rem",color:"#64748b",fontSize:".68rem",fontWeight:800}}><span style={{color:"#102c5c"}}>{active==="programme"?"Overview":active==="readiness"?"Maturity":active==="evidence"?"Proof":active==="execution"?"Priority":active==="technology"?"System": "Authority"}</span><span>•</span><span>6-level stakeholder depth: overview → raw PMO</span></div>

  {active==="programme"&&<div className={styles.tabPanel}>
   <section className={styles.externalHero}><div><div className={styles.eyebrow}>30-second company view</div><h2 className={styles.externalTitle}>Precision production infrastructure + operating software for mud-crab aquaculture.</h2><p className={styles.externalCopy}>Crabionics is proving integrated technology in a controlled laboratory environment before claiming biological or commercial validation.</p></div><Card accent="warn"><div className={styles.cardLabel}>CURRENT GATE</div><div className={styles.stageValue}>Technology integration → controlled validation</div><Badge tone="warn">Evidence boundary</Badge></Card></section>
   <section className={styles.commandGrid}><Card accent="warn"><div className={styles.commandKicker}>NOW</div><div className={styles.commandTitle}>Prove the integrated technology loop</div><div className={styles.commandFlow}>Sense → State → Decide → Intervene → Outcome</div></Card><Card><div className={styles.commandKicker}>NEXT PROOF</div><div className={styles.commandTitle}>Controlled laboratory evidence</div><div className={styles.commandSub}>Reproducible runtime evidence on the governed integration path.</div></Card><Card accent="risk"><div className={styles.commandKicker}>BIGGEST UNKNOWN</div><div className={styles.commandTitle}>Biological performance</div><div className={styles.commandSub}>No biological claim without measured experimental evidence.</div></Card><Card><div className={styles.commandKicker}>SUPPORT REQUIRED</div><div className={styles.commandTitle}>Technical + biological + programme execution</div><div className={styles.commandSub}>Integration ownership, biological lead, BIRAC M0 → M1 execution.</div></Card></section>
   <Section eyebrow="Bird's-eye company map" title="How the company works" right={<Badge tone="warn">Closed-loop system</Badge>}><Card><div className={styles.companyMap}>{company.map(([name,role,detail,tone],i)=><React.Fragment key={name}><div className={`${styles.mapNode} ${tone==="good"?styles.mapGood:tone==="warn"?styles.mapWarn:styles.mapRisk}`}><div className={styles.mapNodeName}>{name}</div><div className={styles.mapNodeRole}>{role}</div><div className={styles.mapNodeDetail}>{detail}</div></div>{i<company.length-1&&<div className={styles.mapArrow}>→</div>}</React.Fragment>)}</div><div className={styles.feedbackLoop}><span>Sense</span><b>→</b><span>State</span><b>→</b><span>Decide</span><b>→</b><span>Intervene</span><b>→</b><span>Outcome</span><b>↺</b><span>Learn / validate</span></div><p className={styles.mapCaption}>The intended product is a biological control system: habitat + sensing + decision software + intervention + measured outcome.</p></Card></Section>
   <Section eyebrow="Validation roadmap" title="G0 → G6: the evidence path" right={<Badge tone="warn">Single PMO gate source</Badge>}><p className={styles.cardSub}>Every programme roadmap step maps directly to the same technical/validation gate namespace used by the authoritative PMO. Click any step to open its raw gate record.</p><div className={styles.gateBoard}>{gates.map((g,i)=><GateCard key={g.id} gate={g} index={i} onJump={jumpGate}/>)}</div></Section>
   <Section eyebrow="Risk retirement" title="What the programme is proving, in order"><div className={styles.riskLadder}>{riskLadder.map((x,i)=><div className={`${styles.riskStep} ${i===0?styles.riskCurrent:""}`} key={x}><span>{i+1}</span><div><strong>{x}</strong><small>{i===0?"Current risk boundary":i===1?"Next major uncertainty":"Downstream gate"}</small></div>{i<riskLadder.length-1&&<b>↓</b>}</div>)}</div><p className={styles.cardSub}>Roadmap = evidence sequence. Risk ladder = uncertainty being retired. They are intentionally related, but they answer different questions.</p></Section>
   <Section eyebrow="Programme timeline" title="When the evidence path runs"><p className={styles.cardSub}>Timeline = execution timing. It shows when the BIRAC lane and company validation path intersect without turning milestones into validation claims.</p><div className={styles.timeline}>{timeline.map(([period,title,detail,tone],i)=><div className={styles.timelineRow} key={period}><div className={styles.timelineRail}><span className={`${styles.timelineDot} ${tone==="warn"?styles.mapWarn:tone==="risk"?styles.mapRisk:""}`}>{i+1}</span>{i<timeline.length-1&&<i/>}</div><div className={styles.timelineContent}><div className={styles.timelineTop}><Badge tone={tone}>{period}</Badge><strong>{title}</strong></div><div className={styles.timelineDetail}>{detail}</div></div></div>)}</div></Section>
   <Section eyebrow="Decision & support required" title="The stakeholder decision layer"><div className={styles.decisionGrid}><Card accent="warn"><div className={styles.cardLabel}>CURRENT DECISION</div><div className={styles.cardValue}>Move from architecture/integration into controlled laboratory proof.</div></Card><Card><div className={styles.cardLabel}>EVIDENCE REQUIRED</div><div className={styles.cardValue}>State → decision → intervention → outcome, reconstructable from governed evidence.</div></Card><Card accent="risk"><div className={styles.cardLabel}>DO NOT CLAIM YET</div><div className={styles.cardValue}>Biological performance, 600-box repeatability or commercial validation.</div></Card><Card><div className={styles.cardLabel}>SUPPORT THAT MATTERS</div><div className={styles.cardValue}>Technical integration, biological leadership, BIRAC execution and validation resources.</div></Card></div></Section>
   <Section eyebrow="Capital logic" title="What capital is supposed to buy"><p className={styles.cardSub}>Capital flow = funding logic. It answers what evidence a capital stage is intended to unlock; it is not a duplicate of the validation ladder.</p><Card><div className={styles.capitalFlow}>{capital.map((x,i)=><React.Fragment key={x}><div className={`${styles.capitalStep} ${i===0?styles.capitalCurrent:""}`}><span>{i+1}</span><div>{x}</div></div>{i<capital.length-1&&<div className={styles.capitalArrow}>→</div>}</React.Fragment>)}</div><div className={styles.capitalFooter}><Badge tone="warn">INVESTMENT LOGIC</Badge><span>Validation capital should buy evidence at the next boundary, not simply more features.</span></div></Card></Section>
  </div>}

  {active==="readiness"&&<div className={styles.tabPanel}>
   <Section eyebrow="Maturity at a glance" title="Different parts of Crabionics are at different evidence levels" right={<Badge tone="warn">No single company-wide TRL</Badge>}><Card><div className={styles.maturityGrid}>{maturity.map(([name,value,tone])=><div className={styles.maturityRow} key={name}><div className={styles.maturityName}>{name}</div><div className={styles.maturityValue}>{value}</div><Badge tone={tone}>{tone==="good"?"GREEN":tone==="warn"?"AMBER":"RED"}</Badge></div>)}</div><p className={styles.cardSub}>TRL is a lens, not the company state. Use subsystem evidence until the system earns a defensible maturity claim.</p></Card></Section>
   <Section eyebrow="Validation ladder" title="G0 → G6 readiness"><p className={styles.cardSub}>This is the same gate dataset used by Programme and the PMO view. There is no second six-step ladder.</p><div className={styles.gateBoard}>{gates.map((g,i)=><GateCard key={g.id} gate={g} index={i} onJump={jumpGate}/>)}</div></Section>
   <Section eyebrow="Readiness by stakeholder" title="What each reviewer needs to see"><div className={styles.grid4}><Card><div className={styles.cardLabel}>INVESTOR</div><div className={styles.cardSub}>Risk retired → risk remaining → what the next capital tranche buys.</div></Card><Card><div className={styles.cardLabel}>ADVISOR / BIRAC / KIIT-TBI</div><div className={styles.cardSub}>Milestone → evidence boundary → dependency → decision.</div></Card><Card><div className={styles.cardLabel}>TECHNICAL REVIEWER</div><div className={styles.cardSub}>Subsystem maturity → integration gap → acceptance evidence.</div></Card><Card><div className={styles.cardLabel}>PROCESSOR</div><div className={styles.cardSub}>Predictable supply → consistency → traceability → economics.</div></Card></div></Section>
  </div>}

  {active==="evidence"&&<div className={styles.tabPanel}><Section eyebrow="Evidence model" title="Claim → proof, not claim → presentation"><div className={styles.chain}>{claimChain.map((x,i)=><div className={styles.chainStep} key={x}><span>{i+1}</span><div>{x}</div></div>)}</div></Section><Section eyebrow="AquaOS evidence gate" title="State → decision → intervention → outcome" right={<Badge tone="warn">Mandatory for Dataset-001</Badge>}><Card><div className={styles.outcomeChain}>{outcomeChain.map((x,i)=><React.Fragment key={x}><div className={`${styles.outcomeStep} ${i===5?styles.outcomeBiology:""}`}><span>{i+1}</span><strong>{x}</strong></div>{i<outcomeChain.length-1&&<div className={styles.outcomeArrow}>→</div>}</React.Fragment>)}</div><div className={styles.fieldGrid}><div><b>Minimum record</b><span>Biological state · AquaOS decision · intervention/action · timestamp · response · biological outcome</span></div><div><b>Governance</b><span>Confidence · human override · identity/correlation/provenance where applicable</span></div></div></Card></Section><Section eyebrow="Evidence discipline" title="Known / observed / inferred / unknown / needs experiment"><div className={styles.grid5}><Card><Badge tone="good">KNOWN</Badge><div className={styles.cardSub}>Recorded in authoritative PMO/repository state.</div></Card><Card><Badge>OBSERVED</Badge><div className={styles.cardSub}>Directly visible in current issues, commits or evidence.</div></Card><Card><Badge tone="warn">INFERRED</Badge><div className={styles.cardSub}>Interpretation derived from observed facts.</div></Card><Card><Badge tone="risk">UNKNOWN</Badge><div className={styles.cardSub}>Not established by the available source.</div></Card><Card><Badge tone="warn">NEEDS EXPERIMENT</Badge><div className={styles.cardSub}>Requires a defined experiment and evidence artifact.</div></Card></div></Section><Section eyebrow="Evidence boundary" title="Established vs not yet proven"><div className={styles.grid2}><Card accent="good"><Badge tone="good">ESTABLISHED</Badge><div className={styles.cardSub}>Governance foundation; BIRAC execution lane; AquaOS lifecycle; synthetic closed-loop integration; validation architecture.</div></Card><Card accent="risk"><Badge tone="risk">NOT YET PROVEN</Badge><div className={styles.cardSub}>Physical sensor/actuator loop; biological response; repeatable production performance; 600-box economics; processor/customer validation.</div></Card></div></Section></div>}

  {active==="execution"&&<div className={styles.tabPanel}><section className={styles.commandBanner}><div><div className={styles.eyebrow}>Execution command centre</div><h2>Execute the current plan. Use evidence to select the next gate.</h2></div><Badge tone="warn">Current plan wins</Badge></section><Section eyebrow="Immediate work" title="NOW / NEXT / LATER"><div className={styles.grid3}><Card accent="warn"><div className={styles.commandKicker}>NOW</div><div className={styles.commandTitle}>BIRAC M0 → M1 + integrated lab proof</div><div className={styles.commandSub}>Release readiness, monitoring/control prototype and governed integration evidence.</div></Card><Card><div className={styles.commandKicker}>NEXT</div><div className={styles.commandTitle}>Controlled validation experiments</div><div className={styles.commandSub}>Run the approved experiment, capture raw evidence and preserve provenance.</div></Card><Card accent="risk"><div className={styles.commandKicker}>LATER</div><div className={styles.commandTitle}>Biology → 600-box → commercial</div><div className={styles.commandSub}>Downstream gates; do not pull them forward without evidence.</div></Card></div></Section><Section eyebrow="Explicit signals only" title="Risk / attention" right={<Badge tone={data.blockers.length?"risk":"good"}>{data.blockers.length?`${data.blockers.length} flagged`:"No explicit P0/blocker labels"}</Badge>}><Issues issues={data.blockers}/>{data.stale.length>0&&<div className={styles.staleNote}><Badge tone="warn">STALE SIGNAL</Badge><span>{data.stale.length} open issues have not reported an update for at least 7 days. Staleness is an observation, not proof of blockage.</span></div>}</Section><Section eyebrow="Observed movement" title="Recent governed work"><Issues issues={data.recentlyUpdated}/></Section></div>}

  {active==="technology"&&<div className={styles.tabPanel}><Section eyebrow="Bird's-eye system" title="Habitat → Sense → Decide → Intervene → Outcome"><Card><div className={styles.companyMap}>{company.map(([name,role,detail,tone],i)=><React.Fragment key={name}><div className={`${styles.mapNode} ${tone==="good"?styles.mapGood:tone==="warn"?styles.mapWarn:styles.mapRisk}`}><div className={styles.mapNodeName}>{name}</div><div className={styles.mapNodeRole}>{role}</div><div className={styles.mapNodeDetail}>{detail}</div></div>{i<company.length-1&&<div className={styles.mapArrow}>→</div>}</React.Fragment>)}</div><div className={styles.feedbackLoop}><span>Input / sensor</span><b>→</b><span>Observation</span><b>→</b><span>Event</span><b>→</b><span>Decision</span><b>→</b><span>Action / command</span><b>→</b><span>Acknowledgement / outcome</span></div></Card></Section><Section eyebrow="Architecture doctrine" title="Model-agnostic but biology-specific"><Card accent="warn"><div className={styles.principle}>Models, sensors, controllers and actuators are replaceable infrastructure. The intended control/data moat is the biological ontology, event model, control policies and validated outcomes.</div><p className={styles.cardSub}>This is a governance/architecture principle, not evidence that a moat has already been earned.</p></Card></Section><Section eyebrow="Hardware resilience" title="Modular components + supply-risk control"><div className={styles.grid4}><Card><div className={styles.cardLabel}>INTERFACE</div><div className={styles.cardValue}>Standard abstraction layer</div></Card><Card><div className={styles.cardLabel}>SOURCING</div><div className={styles.cardValue}>Single-source / dual-source tracked</div></Card><Card><div className={styles.cardLabel}>FX / IMPORT</div><div className={styles.cardValue}>Dependency and exposure tracked</div></Card><Card><div className={styles.cardLabel}>REPLACEMENT</div><div className={styles.cardValue}>Criticality + substitute path</div></Card></div></Section><Section eyebrow="Subsystem truth" title="What each layer owns"><div className={styles.stack}>{company.map(([name,role,detail,tone])=><div className={styles.stackRow} key={name}><div className={styles.stackName}>{name}</div><div className={styles.stackRole}>{role}</div><div className={styles.stackStatus}>{detail} · <Badge tone={tone}>{tone==="good"?"implemented layer":tone==="warn"?"integration / evidence pending":"biological proof pending"}</Badge></div></div>)}</div></Section></div>}

  {active==="pmo"&&<div className={styles.tabPanel}>
   <Section eyebrow="PMO source" title="Authoritative programme state"><div style={{display:"flex",gap:".55rem",flexWrap:"wrap",alignItems:"center"}}><Badge tone="good">RAW / AUTHORITATIVE</Badge><span className={styles.cardSub} style={{margin:0}}>PMO tab is the unfiltered source view. Execution is curated and prioritized.</span></div><div className={styles.sourceMini}><a href={data.pmoStateUrl} target="_blank" rel="noreferrer">CURRENT_STATE.md</a><a href={data.pmoYamlUrl} target="_blank" rel="noreferrer">PMO YAML</a></div><Card><Markdown text={data.strategic}/></Card></Section>
   <Section eyebrow="Authoritative gate ladder" title="G0 → G6 technical / validation gates"><div className={styles.gateBoard}>{gates.map((g,i)=><div id={`gate-${g.id}`} key={g.id}><GateCard gate={g} index={i} onJump={()=>undefined}/></div>)}</div></Section>
   <Section eyebrow="Execution posture" title="Current governed plan"><Card accent="warn"><div className={styles.cardLabel}>SCOPE-CONTROL DOCTRINE</div>{scopeRules.length?<ul style={{margin:".55rem 0 0",paddingLeft:"1.15rem"}}>{scopeRules.map((x,i)=><li key={i} style={{margin:".35rem 0",color:"#334155"}}>{inlineMarkdown(x)}</li>)}</ul>:<Markdown text={data.execution}/>}</Card></Section>
   <Section eyebrow="Funding boundary" title="BIRAC execution lane"><Card accent="warn"><div className={styles.cardLabel}>FUNDING RULES</div><Markdown text={data.funding}/></Card></Section>
   <Section eyebrow="Validation" title="Authoritative raw gate source"><Card><Markdown text={data.validation}/></Card></Section>
   <Section eyebrow="Technology" title="Core technology truth"><Card><Markdown text={data.technology}/></Card></Section>
   <Section eyebrow="Raw work feed" title="Open PMO issues" right={<Badge tone={data.githubLive?"good":"warn"}>{data.githubLive?`${data.issues.length} open`:"GitHub feed unavailable"}</Badge>}><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:".7rem",marginBottom:".7rem"}}><span className={styles.cardSub} style={{margin:0}}>Showing {showAllPmo?data.issues.length:Math.min(8,data.issues.length)} of {data.issues.length} open PMO issues.</span><button type="button" onClick={()=>setShowAllPmo(v=>!v)} style={{border:"1px solid #dbe5ef",borderRadius:".65rem",background:"#fff",padding:".45rem .65rem",fontWeight:850,color:"#087f98",cursor:"pointer"}}>{showAllPmo?"Collapse":"Show all"}</button></div><Issues issues={data.issues} limit={showAllPmo?data.issues.length:8}/></Section>
  </div>}

  <footer className={styles.footer}><strong>Control rule:</strong> PMO defines company state; owning repositories define implementation truth; runtime/raw evidence defines operational proof. The Control Tower is only a projection. <a href={data.pmoStateUrl} target="_blank" rel="noreferrer">Open PMO boot file</a>.</footer>
 </div></main>
}
