"use client";

import React, { useState } from "react";
import styles from "./control-tower-v3.module.css";

type Tone = "neutral" | "good" | "warn" | "risk";
export type TowerIssue = { number: number; title: string; state: string; labels: string[]; url: string; updated_at?: string };
export type TowerData = { live:boolean; githubLive:boolean; pmoState:string|null; pmoYaml:string|null; pmoStateUrl:string; pmoYamlUrl:string; strategic:string; funding:string; execution:string; validation:string; technology:string; issues:TowerIssue[]; blockers:TowerIssue[]; stale:TowerIssue[]; recentlyUpdated:TowerIssue[]; repoIssues:Record<string,TowerIssue[]> };

function Badge({children,tone="neutral"}:{children:React.ReactNode;tone?:Tone}){return <span className={`${styles.badge} ${tone==="good"?styles.good:tone==="warn"?styles.warn:tone==="risk"?styles.risk:""}`}>{children}</span>}
function Card({children,soft=false}:{children:React.ReactNode;soft?:boolean}){return <div className={`${styles.card} ${soft?styles.cardSoft:""}`}>{children}</div>}
function Section({eyebrow,title,right,children}:{eyebrow:string;title:string;right?:React.ReactNode;children:React.ReactNode}){return <section className={styles.section}><div className={styles.sectionHead}><div><div className={styles.eyebrow}>{eyebrow}</div><h2 className={styles.sectionTitle}>{title}</h2></div>{right}</div>{children}</section>}

function inlineMarkdown(text:string){
 const parts=text.split(/(\*\*[^*]+\*\*|`[^`]+`)/g);
 return parts.map((part,i)=>{
  if(part.startsWith("**")&&part.endsWith("**")) return <strong key={i}>{part.slice(2,-2)}</strong>;
  if(part.startsWith("`")&&part.endsWith("`")) return <code key={i}>{part.slice(1,-1)}</code>;
  return <React.Fragment key={i}>{part}</React.Fragment>;
 });
}

function Markdown({text}:{text:string}){
 const lines=text.split(/\r?\n/);
 const rows:string[][]=[];
 let inTable=false;
 const blocks:React.ReactNode[]=[];
 lines.forEach((raw,i)=>{
  const line=raw.trim();
  if(!line){inTable=false;return;}
  const cells=line.split("|").map(x=>x.trim()).filter((x,j,a)=>!(j===0&&x==="")&&!(j===a.length-1&&x===""));
  const isTable=cells.length>=2;
  const isSeparator=isTable&&cells.every(x=>/^:?-{3,}:?$/.test(x));
  if(isSeparator){inTable=true;return;}
  if(isTable && (inTable || /\|/.test(line))){
   if(!inTable) rows.length=0;
   rows.push(cells);
   inTable=true;
   const next=lines[i+1]?.trim()??"";
   const nextCells=next.split("|").map(x=>x.trim()).filter(Boolean);
   const nextIsSeparator=nextCells.length===cells.length&&nextCells.every(x=>/^:?-{3,}:?$/.test(x));
   if(!nextIsSeparator && i+1<lines.length && !/\|/.test(next)){
    blocks.push(<MarkdownTable key={`table-${i}`} rows={[...rows]}/>);
    rows.length=0;inTable=false;
   }
   return;
  }
  if(inTable){blocks.push(<MarkdownTable key={`table-${i}`} rows={[...rows]}/>);rows.length=0;inTable=false;}
  if(line.startsWith("### ")) blocks.push(<h4 key={i}>{inlineMarkdown(line.slice(4))}</h4>);
  else if(line.startsWith("## ")) blocks.push(<h3 key={i}>{inlineMarkdown(line.slice(3))}</h3>);
  else if(line.startsWith("# ")) blocks.push(<h3 key={i}>{inlineMarkdown(line.slice(2))}</h3>);
  else if(/^[-*] /.test(line)) blocks.push(<li key={i}>{inlineMarkdown(line.slice(2))}</li>);
  else blocks.push(<p key={i}>{inlineMarkdown(line)}</p>);
 });
 if(rows.length) blocks.push(<MarkdownTable key="table-final" rows={rows}/>);
 return <div className={styles.markdown}>{blocks}</div>;
}

function MarkdownTable({rows}:{rows:string[][]}){if(!rows.length)return null;const [head,...body]=rows;return <div className={styles.tableScroll}><table><thead><tr>{head.map((x,i)=><th key={i}>{inlineMarkdown(x)}</th>)}</tr></thead><tbody>{body.map((r,i)=><tr key={i}>{r.map((x,j)=><td key={j}>{inlineMarkdown(x)}</td>)}</tr>)}</tbody></table></div>}
function ageDays(v?:string){return v?Math.floor((Date.now()-new Date(v).getTime())/86400000):null}
function Issues({issues,limit=10}:{issues:TowerIssue[];limit?:number}){return issues.length?<div className={styles.grid2}>{issues.slice(0,limit).map(x=><a key={x.number} href={x.url} target="_blank" rel="noreferrer" className={styles.issue}><div className={styles.issueTitle}>#{x.number} · {x.title}</div><div className={styles.issueMeta}>{x.labels.length?x.labels.join(" · "):"No labels"} · Updated {ageDays(x.updated_at)??"?"}d ago</div></a>)}</div>:<Card soft><div className={styles.cardSub}>No governed open work returned by GitHub.</div></Card>}

const tabs=["programme","readiness","evidence","execution","technology","pmo"] as const;
const maturity:Array<[string,string,Tone]>= [["Software","Lifecycle implemented; runtime validation pending","warn"],["Technology","Controlled integration","warn"],["Hardware","Integration pending","warn"],["Biology","Not yet validated","risk"],["Production","Not yet validated","risk"],["Commercial","Early validation","risk"],["IP","Evidence / reconciliation","warn"],["Corporate","Diligence / reconciliation","warn"],["Funding","Validation capital","warn"]];
const roadmap=["Technology integration","Controlled lab validation","Biological validation","600-box production validation","Processor / customer validation","Repeatable commercial production","Scale"];
const claimChain=["Claim / requirement","Implementation","Experiment","Raw evidence","Verdict","Economic implication"];
const outcomeChain=["Biological state","AquaOS decision","Intervention / action","Timestamp","Response","Biological outcome","Confidence","Human override"];
const company:Array<[string,string,string,Tone]>= [["Habitat","Production environment","Physical foundation","warn"],["CrabSense","Sense","Telemetry / observations","warn"],["AquaOS","State → Decide","Decision + event layer","warn"],["CrabPod","Intervene","Actuator / command execution","warn"],["BioPod","Outcome","Biological response + evidence","risk"]];
const timeline:Array<[string,string,string,Tone]>=[["NOW","Technology integration","AOS-008 / AOS-011 → CrabPod runtime → integrated laboratory proof","warn"],["M0 → M1","BIRAC / IHMS","Release readiness and monitoring/control prototype","warn"],["M1 → M2","Evidence generation","Dashboard, alerting and controlled validation","neutral"],["M2 → M3","Pilot validation","Biological validation, pilot evidence and final deliverables","neutral"],["POST-M3","Company scale path","600-box → processor/customer → repeatable commercial production","risk"]];
const capital=["Controlled laboratory proof","Engineering evidence","Biological evidence","Production economics","Processor / customer evidence","Repeatable production"];

export default function ControlTowerTabs({data}:{data:TowerData}){
 const [active,setActive]=useState<(typeof tabs)[number]>("programme");
 const status=!data.live?"DEGRADED · PMO STATE UNAVAILABLE":data.githubLive?"LIVE · PMO + GITHUB":"LIVE · PMO ONLY — GITHUB FEED UNAVAILABLE";
 const repoLabels:Record<string,string>={aquaos:"AquaOS",crabpod:"CrabPod",habitat:"Habitat","crabionics-site":"Website"};
 return <main className={styles.tower}><div className={styles.inner}>
  <header className={styles.hero}><div className={styles.heroTop}><Badge tone={data.live&&data.githubLive?"good":data.live?"warn":"risk"}>{status}</Badge><div className={styles.source}><div className={styles.sourceLabel}>SOURCE AUTHORITY</div><a className={styles.sourceLink} href={data.pmoStateUrl} target="_blank" rel="noreferrer">PMO → CURRENT_STATE.md</a></div></div><div><div className={styles.eyebrow}>Crabionics programme & evidence system</div><h1 className={styles.heroTitle}>Control Tower</h1><p className={styles.heroCopy}>One governed data model, multiple views. Programme state comes from PMO; implementation truth comes from owning repositories; operational proof comes from evidence.</p></div></header>
  <nav className={styles.tabs} aria-label="Control Tower views">{tabs.map(id=><button key={id} type="button" className={`${styles.tab} ${active===id?styles.tabActive:""}`} onClick={()=>setActive(id)}>{id[0].toUpperCase()+id.slice(1)}</button>)}</nav>

  {active==="programme"&&<div className={styles.tabPanel}>
   <section className={styles.externalHero}><div><div className={styles.eyebrow}>Universal stakeholder view</div><h2 className={styles.externalTitle}>Precision production infrastructure + operating software for mud-crab aquaculture.</h2><p className={styles.externalCopy}>Crabionics is currently proving integrated technology in a controlled laboratory environment before claiming biological or commercial validation.</p></div><div className={styles.stageCard}><div className={styles.cardLabel}>CURRENT STAGE</div><div className={styles.stageValue}>Technology integration → controlled validation</div><Badge tone="warn">Validation stage</Badge></div></section>
   <Section eyebrow="Bird's-eye company map" title="How the company works" right={<Badge tone="warn">Visual system map</Badge>}><Card><div className={styles.companyMap}>{company.map(([name,role,detail,tone],i)=><React.Fragment key={name}><div className={`${styles.mapNode} ${tone==="good"?styles.mapGood:tone==="warn"?styles.mapWarn:styles.mapRisk}`}><div className={styles.mapNodeName}>{name}</div><div className={styles.mapNodeRole}>{role}</div><div className={styles.mapNodeDetail}>{detail}</div></div>{i<company.length-1&&<div className={styles.mapArrow}>→</div>}</React.Fragment>)}</div><div className={styles.mapFlow}><span>Sense</span><b>→</b><span>State</span><b>→</b><span>Decide</span><b>→</b><span>Intervene</span><b>→</b><span>Outcome</span></div><p className={styles.mapCaption}>One production system: physical habitat + sensing + decision software + intervention + biological evidence.</p></Card></Section>
   <div className={styles.grid4}><Card><div className={styles.cardLabel}>Immediate objective</div><div className={styles.cardValue}>BIRAC M0 → M1 + integrated laboratory proof</div></Card><Card><div className={styles.cardLabel}>Next proof</div><div className={styles.cardValue}>Sense → State → Decide → Intervene → Outcome</div></Card><Card><div className={styles.cardLabel}>600-box</div><div className={styles.cardValue}>Downstream / gated</div></Card><Card><div className={styles.cardLabel}>Current attention</div><div className={styles.cardValue}>{data.blockers.length?`${data.blockers.length} explicit blocker/P0 signal(s)`:"No explicit P0/blocker labels"}</div></Card></div>
   <Section eyebrow="Maturity at a glance" title="Different parts of Crabionics are at different evidence levels" right={<Badge tone="warn">No single company-wide TRL</Badge>}><Card><div className={styles.maturityGrid}>{maturity.map(([name,value,tone])=><div className={styles.maturityRow} key={name}><div className={styles.maturityName}>{name}</div><div className={styles.maturityValue}>{value}</div><Badge tone={tone}>{tone==="warn"?"AMBER":tone==="risk"?"RED":"GREEN"}</Badge></div>)}</div><p className={styles.cardSub}>A single TRL would hide physical integration, biological and commercial gaps. Keep maturity multidimensional until the whole system earns a defensible maturity claim.</p></Card></Section>
   <Section eyebrow="Validation roadmap" title="Technology → commercial repeatability"><div className={styles.roadmap}>{roadmap.map((x,i)=><div className={`${styles.roadmapStep} ${i===0?styles.roadmapCurrent:""}`} key={x}><span>{i+1}</span><div>{x}</div>{i===0&&<Badge tone="warn">NOW</Badge>}{i>0&&i<5&&<Badge>GATE</Badge>}</div>)}</div></Section>
   <Section eyebrow="Programme timeline" title="BIRAC timeline + company validation path"><div className={styles.timeline}>{timeline.map(([period,title,detail,tone],i)=><div className={styles.timelineRow} key={period}><div className={styles.timelineRail}><span className={`${styles.timelineDot} ${tone==="warn"?styles.mapWarn:tone==="risk"?styles.mapRisk:""}`}>{i+1}</span>{i<timeline.length-1&&<i/>}</div><div className={styles.timelineContent}><div className={styles.timelineTop}><Badge tone={tone}>{period}</Badge><strong>{title}</strong></div><div className={styles.timelineDetail}>{detail}</div></div></div>)}</div><p className={styles.timelineNote}>BIRAC M0–M3 is a funded execution lane. The broader company path continues through biological validation, 600-box production validation, processor/customer evidence and repeatable commercial production.</p></Section>
   <Section eyebrow="What capital unlocks" title="Capital → evidence → risk retirement"><Card><div className={styles.capitalFlow}>{capital.map((x,i)=><React.Fragment key={x}><div className={`${styles.capitalStep} ${i===0?styles.capitalCurrent:""}`}><span>{i+1}</span><div>{x}</div></div>{i<capital.length-1&&<div className={styles.capitalArrow}>↓</div>}</React.Fragment>)}</div><div className={styles.capitalFooter}><Badge tone="warn">INVESTMENT LOGIC</Badge><span>Validation capital should buy evidence at the next boundary, not simply more features or architecture.</span></div></Card></Section>
   <Section eyebrow="Evidence boundaries" title="What is proven vs what remains"><div className={styles.grid2}><Card><Badge tone="good">ESTABLISHED</Badge><div className={styles.cardSub}>Governance foundation; BIRAC execution lane; AquaOS operational lifecycle; synthetic closed-loop integration; validation architecture.</div></Card><Card><Badge tone="risk">NOT YET PROVEN</Badge><div className={styles.cardSub}>Physical sensor/actuator loop, biological response, repeatable production performance, 600-box economics and processor/customer validation.</div></Card></div></Section>
   <Section eyebrow="Evidence chain" title="Claim → proof"><div className={styles.roadmap}>{claimChain.map((x,i)=><div className={styles.roadmapStep} key={x}><span>{i+1}</span><div>{x}</div></div>)}</div></Section>
   <Section eyebrow="Stakeholder lens" title="What this page answers"><div className={styles.grid4}><Card><div className={styles.cardLabel}>Investor</div><div className={styles.cardSub}>Risk retired, risk remaining, and what capital buys next.</div></Card><Card><div className={styles.cardLabel}>Advisor / BIRAC / KIIT-TBI</div><div className={styles.cardSub}>Milestone, evidence boundary, dependencies and decisions.</div></Card><Card><div className={styles.cardLabel}>Technical reviewer</div><div className={styles.cardSub}>Subsystem maturity and physical integration gap.</div></Card><Card><div className={styles.cardLabel}>Processor</div><div className={styles.cardSub}>Path toward predictable supply, consistency, traceability and economics.</div></Card></div></Section>
  </div>}

  {active==="readiness"&&<div className={styles.tabPanel}><Section eyebrow="Readiness matrix" title="Crabionics maturity is multidimensional" right={<Badge tone="warn">No single company-wide TRL claim</Badge>}><Card><p className={styles.readinessNote}>A single TRL would hide differences between software, physical integration, biology and commercial readiness.</p><div className={styles.readinessGrid}>{maturity.map(([name,value,tone])=><div className={styles.readinessRow} key={name}><div className={styles.readinessName}>{name}</div><div className={styles.readinessValue}>{value}</div><Badge tone={tone}>{tone==="good"?"GREEN":tone==="warn"?"AMBER":"RED"}</Badge></div>)}</div></Card></Section><Section eyebrow="Readiness path" title="Evidence progression"><div className={styles.roadmap}>{["Integrated prototype","Relevant controlled environment","Biological validation","Repeatable production","Commercial repeatability","Scale-ready system"].map((x,i)=><div className={styles.roadmapStep} key={x}><span>{i+1}</span><div>{x}</div></div>)}</div></Section></div>}

  {active==="evidence"&&<div className={styles.tabPanel}><Section eyebrow="Evidence model" title="Known / Observed / Inferred / Unknown / Needs experiment"><div className={styles.grid5}>{[["KNOWN","Authoritative PMO or repository state","good"],["OBSERVED","Directly visible evidence","neutral"],["INFERRED","Interpretation from observations","warn"],["UNKNOWN","Not established","risk"],["NEEDS EXPERIMENT","Requires a defined experiment","warn"]].map(([a,b,t])=><Card key={a}><Badge tone={t as Tone}>{a}</Badge><div className={styles.cardSub}>{b}</div></Card>)}</div></Section><Section eyebrow="AquaOS Dataset-001" title="Mandatory intervention → outcome chain" right={<Badge tone="warn">Evidence gate</Badge>}><Card><div className={styles.chain}>{outcomeChain.map((x,i)=><div className={styles.chainStep} key={x}><span>{i+1}</span>{x}</div>)}</div><p className={styles.cardSub}>The chain must be reconstructable with identity, correlation, provenance, comparator, implementation version, conditions, measured outcome and verdict.</p></Card></Section><Section eyebrow="Evidence chain" title="Claim → proof"><div className={styles.roadmap}>{claimChain.map((x,i)=><div className={styles.roadmapStep} key={x}><span>{i+1}</span><div>{x}</div></div>)}</div></Section></div>}

  {active==="execution"&&<div className={styles.tabPanel}><div className={styles.grid4}><Card><div className={styles.cardLabel}>NOW</div><div className={styles.cardValue}>BIRAC M0 → M1</div></Card><Card><div className={styles.cardLabel}>Technical dependency</div><div className={styles.cardValue}>AOS-008 → AOS-011 → CrabPod runtime</div></Card><Card><div className={styles.cardLabel}>Scientific owner</div><div className={styles.cardValue}>Pending appointment</div></Card><Card><div className={styles.cardLabel}>Operating model</div><div className={styles.cardValue}>Programme execution + technical workstream</div></Card></div><Section eyebrow="Current execution posture" title="What happens next"><Card><Markdown text={data.execution}/></Card></Section><Section eyebrow="Validation dependencies" title="What can block the next proof"><Card><Markdown text={data.validation}/></Card></Section><Section eyebrow="Live work" title="Current governed PMO issues" right={<Badge tone={data.githubLive?"good":"warn"}>{data.githubLive?`${data.issues.length} open PMO issues`:"Issue feed unavailable"}</Badge>}>{data.githubLive?<Issues issues={data.issues}/>:<Card soft>GitHub issue status could not be verified.</Card>}</Section><Section eyebrow="Risk / attention" title="Explicit signals only"><div className={styles.grid2}>{data.blockers.length?<Issues issues={data.blockers} limit={8}/>:<Card><Badge tone="good">NO EXPLICIT BLOCKER LABELS</Badge><div className={styles.cardSub}>This does not mean there are no unresolved dependencies.</div></Card>}{data.stale.length?<Card><Badge tone="warn">STALE SIGNAL</Badge><div className={styles.cardSub}>{data.stale.length} open issues have not reported an update for at least 7 days.</div></Card>:null}</div></Section></div>}

  {active==="technology"&&<div className={styles.tabPanel}><Section eyebrow="Technology spine" title="Subsystem roles"><div className={styles.stack}>{[["Habitat","Physical production environment","Engineering / RAS physical truth."],["CrabSense","Observation / telemetry","Sensing, identity and data capture."],["AquaOS","Event / state / decision layer","Operational lifecycle, correlation and decisions."],["CrabPod","Command / actuator execution","Physical intervention and acknowledgement."],["BioPod","Biological outcome","Biological response and evidence boundary."]].map(([name,role,status])=><div className={styles.stackRow} key={name}><div className={styles.stackName}>{name}</div><div className={styles.stackRole}>{role}</div><div className={styles.stackStatus}>{status}</div></div>)}</div></Section><Section eyebrow="Core technology truth" title="What the PMO currently says"><Card><Markdown text={data.technology}/></Card></Section><Section eyebrow="Integration contract" title="Critical dependency"><Card><div className={styles.principle}>AOS-008 → AOS-011 → CrabPod runtime → integrated proof</div><div className={styles.cardSub}>The visual map exposes the dependency; owning repositories remain implementation authority.</div></Card></Section></div>}

  {active==="pmo"&&<div className={styles.tabPanel}><Section eyebrow="PMO source" title="Authoritative programme state"><Card><div className={styles.sourceMini}><a href={data.pmoStateUrl} target="_blank" rel="noreferrer">CURRENT_STATE.md</a><a href={data.pmoYamlUrl} target="_blank" rel="noreferrer">PMO YAML</a></div><Markdown text={data.strategic}/></Card></Section><Section eyebrow="Funding boundary" title="PMO funding posture"><Card><Markdown text={data.funding}/></Card></Section><Section eyebrow="Live execution" title="Current governed PMO work" right={<Badge tone={data.githubLive?"good":"warn"}>{data.githubLive?`${data.issues.length} open PMO issues`:"Issue feed unavailable"}</Badge>}>{data.githubLive?<Issues issues={data.issues}/>:<Card soft>Issue feed unavailable. Do not interpret this as zero open work.</Card>}</Section><Section eyebrow="Repository view" title="Open work by owning repository"><div className={styles.grid2}>{Object.entries(data.repoIssues).filter(([repo])=>repo!=="crabionics-pmo").map(([repo,issues])=><Card key={repo}><div className={styles.cardLabel}>{repoLabels[repo]??repo}</div><div className={styles.cardValue}>{issues.length} open issue(s)</div>{issues.slice(0,4).map(issue=><a key={issue.number} href={issue.url} target="_blank" rel="noreferrer" className={styles.issue} style={{marginTop:".6rem"}}><div className={styles.issueTitle}>#{issue.number} · {issue.title}</div></a>)}</Card>)}</div></Section></div>}

  <footer className={styles.footer}><strong>Control rule:</strong> PMO defines company state; owning repositories define implementation truth; runtime/raw evidence defines operational proof. The Control Tower is only a projection. <a href={data.pmoStateUrl} target="_blank" rel="noreferrer">Open PMO boot file</a>.</footer>
 </div></main>
}