import type {Metadata} from "next";
import {Section,Action,Figure,Network,Icon,styles as s} from "./components/public/Public";
import WorldHero from "./components/public/WorldHero";
import OperatingLoop from "./components/public/OperatingLoop";
export const metadata:Metadata={title:"Crabionics",description:"Crabionics is developing mud-crab production infrastructure: habitat, environmental observation, operator-governed intervention and operating records.",alternates:{canonical:"/"}};
export default function HomePage(){return <div className={s.page} data-page="home"><WorldHero/>
<Section pale><div className={s.editorial}><div><p className={s.eyebrow}>The production environment</p><h2>Biology, water and the people doing the work.</h2></div><p>Mud-crab production brings together animal behaviour, habitat, water conditions, handling and operator decisions. These need to be understood together.</p><p>Crabionics develops the physical environment and the tools around it: observation, local action and a useful record of what happened.</p></div></Section>
<Section dark><div className={s.heading}><div><p className={s.eyebrow}>The connected system</p><h2>Conditions. Decisions.<br/>Action. Observation.</h2></div><p>The Loop links the production setting, what is observed, the operator’s decision and the physical response. Water treatment supports the environment where the setting requires it.</p></div><div className={s.split}><div><Figure src="/photos/isolation-box.jpg" alt="Mud crab in a blue individual habitat." className={s.detailImage}/><div className={s.actions}><Action href="/system" secondary>Meet the system</Action></div></div><OperatingLoop/></div></Section>
<Section><div className={s.heading}><div><p className={s.eyebrow}>The development programme</p><h2>Build, observe and learn<br/>in defined settings.</h2></div><p>System integration, biological performance and commercial fit each have their own questions. Current work connects research, pond learning and controlled-finishing validation.</p></div><div className={s.rows}>{[["01","Research & integration","Funded IHMS work examines how the physical system, sensing and operating routines fit together."],["02","Biological & production learning","Pond and controlled-finishing studies examine cohort performance, handling, conditions and operating records."],["03","Partners & commercial fit","Production partners and downstream conversations help define requirements, responsibilities and the commercial questions to test."]].map(([n,t,p])=><article className={s.row} key={n}><span>{n}</span><h3>{t}</h3><p>{p}</p></article>)}</div><div className={s.actions}><Action href="/validation">Explore the validation programme</Action><Action href="/company" secondary>People behind the work</Action></div></Section>
<Section pale><div className={s.heading}><div><p className={s.eyebrow}>Future deployment</p><h2>A wider production connection.</h2></div><p>The longer-term direction connects seed and nursery, farmer production, controlled finishing and downstream market requirements.</p></div><Network compact/><div className={s.actions}><Action href="/producers">Explore production partnerships</Action></div></Section>
<Section><p className={s.eyebrow}>Get involved</p><h2>Find your place in the work.</h2><div className={s.doors}>{[["pond","Producers & operators","Discuss a pond partnership, finishing context or grow-out beta interest.","/producers"],["research","Research & institutions","Bring a biological question, research setting or public programme.","/contact#institutions"],["habitat","Investors","Understand the company, infrastructure and development pathway.","/investors"]].map(([icon,t,p,href])=><article className={s.door} key={t}><Icon name={icon as "pond"|"research"|"habitat"}/><h3>{t}</h3><p>{p}</p><a href={href}>Explore the conversation →</a></article>)}</div></Section></div>}
