import Image from "next/image";
import Link from "next/link";

const audienceDoors = [
  ["For Producers", "Understand what the architecture is designed to change in mud-crab production.", "/producers"],
  ["For Research & Pilot Partners", "Explore the validation work and the questions that still need evidence.", "/validation"],
  ["How the System Works", "See how habitat, sensing, edge control and operating software connect.", "/system"],
];

const layers = [
  ["Habitat", "The physical production environment around the crab.", "/photos/isolation-box.jpg"],
  ["CrabSense", "Environmental and operating observations connected to production.", "/photos/sensor-node.jpg"],
  ["CrabPod", "Local hardware for flow, flush and other interventions.", "/photos/ras-plumbing.jpg"],
  ["AquaOS", "Records and workflows connecting conditions, actions and outcomes.", "/aquaos-diagram.png"],
];

export default function HomePage() {
  return <div className="bg-white text-slate-900">
    <section className="relative overflow-hidden bg-[#f5f8fb]"><div className="container-shell grid min-h-[650px] items-center gap-12 py-16 md:grid-cols-[0.92fr_1.08fr] md:py-24"><div className="relative z-10 max-w-2xl"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-[#168bb8]">Crabionics Aquaculture</p><h1 className="mt-5 text-5xl font-semibold leading-[1.02] tracking-[-0.045em] text-[#102C5C] sm:text-6xl lg:text-[4.7rem]">Infrastructure for more controlled mud-crab production.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-600">Crabionics is building an integrated production architecture combining habitat, sensing, edge control and operating software to make critical production conditions and decisions more observable, manageable and repeatable.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/producers" className="rounded-full bg-[#102C5C] px-6 py-3 text-sm font-semibold text-white">For producers</Link><Link href="/system" className="rounded-full border border-slate-300 bg-white px-6 py-3 text-sm font-semibold text-[#102C5C]">How the system works</Link></div></div><div className="relative min-h-[390px] overflow-hidden rounded-[28px] bg-white shadow-[0_30px_80px_rgba(16,44,92,0.16)]"><Image src="/hero-crabionics.png" alt="Crabionics mud-crab production infrastructure" fill priority sizes="(max-width: 1024px) 100vw, 55vw" className="object-cover md:object-[center_68%]" /></div></div></section>

    <section className="border-y border-slate-200 bg-white"><div className="container-shell grid gap-8 py-14 md:grid-cols-[1.05fr_1fr_1fr]"><div><p className="text-sm font-semibold text-[#168bb8]">The production problem</p><h2 className="mt-2 text-2xl font-semibold text-[#102C5C]">Mud-crab production is difficult to control and repeat.</h2></div><p className="text-sm leading-7 text-slate-600">The animal, habitat, water quality and operator action interact continuously. A production system has to make those conditions visible and manageable together.</p><p className="text-sm leading-7 text-slate-600">Crabionics starts with the physical production environment and builds the sensing, edge control and operating layer around it.</p></div></section>

    <section className="bg-white py-20 lg:py-24"><div className="container-shell"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#168bb8]">One architecture</p><h2 className="mt-3 text-4xl font-semibold tracking-[-0.035em] text-[#102C5C] sm:text-5xl">Physical production first. Technology underneath.</h2><p className="mt-5 text-lg leading-8 text-slate-600">The system is not four unrelated products. It is one intended operating architecture from habitat to observation, decision, intervention and production learning.</p></div><div className="mt-10 grid gap-5 md:grid-cols-2 xl:grid-cols-4">{layers.map(([title,description,image])=><article key={title} className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="relative h-44 bg-slate-100"><Image src={image} alt={title} fill sizes="(max-width: 768px) 100vw, 25vw" className="object-cover" /></div><div className="p-6"><h3 className="text-xl font-semibold text-[#102C5C]">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{description}</p></div></article>)}</div><div className="mt-8 rounded-2xl border border-slate-200 bg-[#f8fafc] p-6 text-center text-sm font-semibold text-[#102C5C]">Habitat → CrabSense → AquaOS / decision → CrabPod / intervention → operator → outcome → learning</div></div></section>

    <section className="bg-[#f8fafc] py-20 lg:py-24"><div className="container-shell"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#168bb8]">Choose your path</p><h2 className="mt-3 text-4xl font-semibold tracking-[-0.035em] text-[#102C5C] sm:text-5xl">Start with the question you need answered.</h2></div><div className="mt-10 grid gap-5 lg:grid-cols-3">{audienceDoors.map(([title,description,href])=><Link key={title} href={href} className="group rounded-2xl border border-slate-200 bg-white p-7 shadow-sm transition hover:-translate-y-0.5 hover:border-[#8bcfe4]"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#168bb8]">Crabionics</p><h3 className="mt-4 text-2xl font-semibold text-[#102C5C]">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{description}</p><span className="mt-6 inline-flex text-sm font-semibold text-[#168bb8]">Explore the path →</span></Link>)}</div></div></section>

    <section className="border-y border-slate-200 bg-white py-16 lg:py-20"><div className="container-shell grid gap-10 lg:grid-cols-[0.9fr_1.1fr] lg:items-start"><div><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#168bb8]">Why Crabionics</p><h2 className="mt-3 text-3xl font-semibold text-[#102C5C] sm:text-4xl">A production architecture built around a difficult biological problem.</h2></div><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border border-slate-200 p-6"><h3 className="text-lg font-semibold text-[#102C5C]">Field and R&amp;D history</h3><p className="mt-3 text-sm leading-7 text-slate-600">The company brings together existing field experience, engineering integration work and an operating view of mud-crab production.</p></div><div className="rounded-2xl border border-slate-200 p-6"><h3 className="text-lg font-semibold text-[#102C5C]">Institutional relationships</h3><p className="mt-3 text-sm leading-7 text-slate-600">DPIIT Deep Tech recognition, KIIT-TBI incubation and BIRAC/IHMS support form part of the company’s current R&amp;D context.</p></div></div></div></section>

    <section className="bg-[#102C5C] py-20 text-white lg:py-24"><div className="container-shell grid gap-10 lg:grid-cols-[0.9fr_1.1fr] lg:items-center"><div><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#65c7e8]">Current stage</p><h2 className="mt-3 text-4xl font-semibold text-white sm:text-5xl">Technology integration → controlled validation → preparation for repeatable production.</h2></div><div><p className="text-lg leading-8 text-slate-200">Crabionics is building and integrating the architecture before claiming biological, economic or commercial outcomes. Validation work is designed to establish what the system can support in production.</p><Link href="/validation" className="mt-7 inline-flex rounded-full bg-white px-6 py-3 text-sm font-semibold text-[#102C5C]">See the validation programme</Link></div></div></section>

    <section className="bg-white py-16"><div className="container-shell flex flex-col justify-between gap-6 rounded-3xl border border-slate-200 bg-[#f8fafc] p-8 md:flex-row md:items-center md:p-10"><div><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#168bb8]">Talk to us</p><h2 className="mt-2 text-3xl font-semibold text-[#102C5C]">Discuss a pilot, technical question or research partnership.</h2></div><Link href="/contact" className="inline-flex shrink-0 rounded-full bg-[#102C5C] px-6 py-3 text-sm font-semibold text-white">Talk to us →</Link></div></section>
  </div>;
}
