import type { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = { title: "Crabionics", description: "Crabionics is building a connected production system for mud-crab habitat, observations, local intervention and operating workflows.", alternates: { canonical: "/" } };
import Link from "next/link";

const audienceDoors = [
  ["For mud-crab producers", "See the production jobs the system is being built to support, from habitat and water conditions to records and intervention.", "/producers"],
  ["For pilot and research partners", "Understand the validation settings, questions, measurements and partner conversations still ahead.", "/validation"],
  ["How the system works", "Follow the path from the production environment to observation, decision, intervention and learning.", "/system"],
];

const layers = [
  ["Habitat", "A defined production environment for more consistent handling and observation.", "What it addresses: uncontrolled variation in the physical setting.", "/photos/isolation-box.jpg"],
  ["CrabSense", "Environmental and operating observations linked to a specific production unit.", "What it provides: a clearer record of conditions around the crab.", "/photos/sensor-node.jpg"],
  ["CrabPod", "Local hardware intended to support water movement, flushing and other interventions.", "What it supports: action close to the production environment.", "/photos/ras-plumbing.jpg"],
  ["AquaOS", "Records and workflows that connect conditions, actions and outcomes.", "What it provides: a shared operating record for the people running the work.", "/aquaos-diagram.png"],
];

export default function HomePage() {
  return <div className="bg-white text-slate-900">
    <section className="relative overflow-hidden bg-[#f5f8fb]"><div className="container-shell grid min-h-[560px] items-center gap-10 py-12 md:grid-cols-[1.05fr_0.95fr] md:py-16"><div className="relative z-10 max-w-2xl"><p className="text-sm font-semibold uppercase tracking-[0.18em] text-[#168bb8]">Crabionics Aquaculture</p><h1 className="mt-5 text-5xl font-semibold leading-[1.02] tracking-[-0.045em] text-[#102C5C] sm:text-6xl lg:text-[4.25rem]">Infrastructure for more controlled mud-crab production.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-600">For producers and partners working on a difficult production problem: making habitat, water conditions, intervention and day-to-day decisions easier to observe and manage.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/producers" className="rounded-full bg-[#102C5C] px-6 py-3 text-sm font-semibold text-white transition hover:bg-[#0A1F45]">For producers</Link><Link href="/contact" className="rounded-full border border-[#8bcfe4] bg-[#effafd] px-6 py-3 text-sm font-semibold text-[#102C5C] transition hover:border-[#168bb8] hover:bg-white">Discuss a pilot</Link></div></div><div className="hero-image-panel relative min-h-[360px] overflow-hidden rounded-[22px] border border-[#8bcfe4]/60 bg-white shadow-[0_24px_65px_rgba(16,44,92,0.16)]"><Image src="/hero-crabionics.png" alt="Mud-crab production infrastructure and habitat" fill priority sizes="(max-width: 1024px) 100vw, 55vw" className="object-cover md:object-[center_68%]" /></div></div></section>

    <section className="border-y border-slate-200 bg-[#fbfdfe]"><div className="container-shell grid gap-8 py-12 md:grid-cols-[1.05fr_1fr_1fr]"><div><p className="text-sm font-semibold text-[#168bb8]">The production problem</p><h2 className="mt-2 text-2xl font-semibold text-[#102C5C]">Mud-crab production brings together biology, habitat, water and operator action.</h2></div><p className="text-sm leading-7 text-slate-600">Those factors interact continuously. When the production setting and the operating record are unclear, it becomes harder to see what changed and why.</p><p className="text-sm leading-7 text-slate-600">Crabionics starts with the production environment and builds observation, local intervention and operating workflows around the people responsible for it.</p></div></section>

    <section className="bg-white py-20 lg:py-24"><div className="container-shell"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#168bb8]">The system in plain language</p><h2 className="mt-3 text-4xl font-semibold tracking-[-0.035em] text-[#102C5C] sm:text-5xl">Four connected parts, one production conversation.</h2><p className="mt-5 text-lg leading-8 text-slate-600">Each layer has a different job. Together they are intended to help a producer connect the setting, the observation, the decision, the intervention and the result.</p></div><div className="mt-10 grid gap-5 md:grid-cols-2 xl:grid-cols-4">{layers.map(([title,description,detail,image])=><article key={title} className="overflow-hidden rounded-none border border-slate-200 border-t-4 border-t-[#168bb8] bg-white shadow-[0_16px_40px_rgba(16,44,92,0.07)] transition hover:-translate-y-1 hover:shadow-[0_24px_55px_rgba(16,44,92,0.12)]"><div className="relative h-44 bg-slate-100"><Image src={image} alt={title} fill sizes="(max-width: 768px) 100vw, 25vw" className="object-cover" /></div><div className="p-6"><h3 className="text-xl font-semibold text-[#102C5C]">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{description}</p><p className="mt-4 border-t border-slate-100 pt-4 text-xs leading-5 text-slate-500">{detail}</p></div></article>)}</div><div className="mt-8 border-l-4 border-[#168bb8] bg-[#102C5C] p-6 text-center text-sm font-semibold leading-7 text-white shadow-[0_16px_40px_rgba(16,44,92,0.12)]">Habitat → observation → AquaOS / decision → CrabPod / intervention → operator → outcome → learning</div></div></section>

    <section className="bg-[#f8fafc] py-20 lg:py-24"><div className="container-shell"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#168bb8]">Choose your path</p><h2 className="mt-3 text-4xl font-semibold tracking-[-0.035em] text-[#102C5C] sm:text-5xl">Start with the question you need answered.</h2><p className="mt-5 text-lg leading-8 text-slate-600">The site is organised around the way aquaculture partners usually begin: a production job, a validation question or a need to understand the system.</p></div><div className="mt-10 grid gap-5 lg:grid-cols-3">{audienceDoors.map(([title,description,href])=><Link key={title} href={href} className="group rounded-none border border-slate-200 border-l-4 border-l-[#102C5C] bg-white p-7 shadow-[0_16px_40px_rgba(16,44,92,0.07)] transition hover:-translate-y-1 hover:border-l-[#168bb8] hover:shadow-[0_24px_55px_rgba(16,44,92,0.12)]"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#168bb8]">Explore</p><h3 className="mt-4 text-2xl font-semibold text-[#102C5C]">{title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{description}</p><span className="mt-6 inline-flex text-sm font-semibold text-[#168bb8]">Open this path →</span></Link>)}</div></div></section>

    <section className="border-y border-slate-200 bg-white py-16 lg:py-20"><div className="container-shell grid gap-10 lg:grid-cols-[0.9fr_1.1fr] lg:items-start"><div><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#168bb8]">Why Crabionics</p><h2 className="mt-3 text-3xl font-semibold text-[#102C5C] sm:text-4xl">A production company building the tools around the work.</h2><p className="mt-5 text-lg leading-8 text-slate-600">The emphasis is practical: define the setting, make conditions easier to see, support the next action and keep a useful record of what happened.</p></div><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-2xl border border-slate-200 p-6"><h3 className="text-lg font-semibold text-[#102C5C]">Field and research experience</h3><p className="mt-3 text-sm leading-7 text-slate-600">The company brings together field aquaculture context, system integration and software work around mud-crab production.</p></div><div className="rounded-2xl border border-slate-200 p-6"><h3 className="text-lg font-semibold text-[#102C5C]">Evidence-aware development</h3><p className="mt-3 text-sm leading-7 text-slate-600">Progress in putting the system together, biological learning and commercial demand are treated as separate questions with separate evidence.</p></div></div></div></section>

    <section className="bg-[#102C5C] py-20 text-white lg:py-24"><div className="container-shell grid gap-10 lg:grid-cols-[0.9fr_1.1fr] lg:items-center"><div><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#65c7e8]">Current stage</p><h2 className="mt-3 text-4xl font-semibold text-white sm:text-5xl">Building the system. Learning what it can support.</h2></div><div><p className="text-lg leading-8 text-slate-200">Crabionics is integrating the physical and operating pieces before making broader biological, economic or commercial claims. The next step is disciplined validation in defined production settings.</p><Link href="/validation" className="mt-7 inline-flex rounded-full bg-white px-6 py-3 text-sm font-semibold text-[#102C5C]">See the validation programme</Link></div></div></section>

    <section className="bg-white py-16"><div className="container-shell flex flex-col justify-between gap-6 rounded-3xl border border-slate-200 bg-[#f8fafc] p-8 md:flex-row md:items-center md:p-10"><div><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#168bb8]">Talk to us</p><h2 className="mt-2 text-3xl font-semibold text-[#102C5C]">Discuss a pilot, technical question or research partnership.</h2></div><Link href="/contact" className="inline-flex shrink-0 rounded-full bg-[#102C5C] px-6 py-3 text-sm font-semibold text-white transition hover:bg-[#0A1F45]">Talk to us →</Link></div></section>
  </div>;
}
