import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "For Producers", description: "What the Crabionics production architecture is designed to change for mud-crab producers." };

const jobs = [
  ["Habitat", "Production and handling context", "Crabionics is designing the physical environment around the crab rather than treating production as one uniform biomass.", "Current status: architecture and infrastructure integration. Pilot-specific requirements are defined with each production site."],
  ["CrabSense", "Visibility into conditions", "The sensing layer is intended to connect environmental and operating observations to a defined production context.", "Current status: sensing and telemetry integration. Track-specific sensing requirements are defined as each validation activity is activated."],
  ["CrabPod", "Local operational intervention", "The edge-control layer is designed to support flow, flush and other interventions close to the production environment.", "Current status: hardware/control integration. Deployment responsibilities are defined with each pilot partner."],
  ["AquaOS", "Records and workflows", "AquaOS is being developed to connect records, operating workflows, conditions, actions and outcomes for the operator.", "Current status: operating software in development. It is not presented as autonomous farming or a live production dashboard."],
];

export default function ProducersPage() {
  return <div className="bg-white text-slate-900"><section className="bg-[#f5f8fb] py-24 lg:py-32"><div className="container-shell max-w-5xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#168bb8]">For producers</p><h1 className="mt-4 text-5xl font-semibold tracking-[-0.04em] text-[#102C5C] sm:text-6xl">What changes when production is designed around the crab?</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-slate-600">Crabionics is building a production architecture for the practical work of mud-crab farming: habitat, water conditions, intervention, records and operator decisions.</p></div></section>

    <section className="py-20 lg:py-28"><div className="container-shell"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#168bb8]">Production jobs</p><h2 className="mt-3 text-4xl font-semibold tracking-[-0.035em] text-[#102C5C] sm:text-5xl">The architecture is designed around four operating questions.</h2></div><div className="mt-12 grid gap-5 md:grid-cols-2">{jobs.map(([title,subtitle,body,status],index)=><article key={title} className="rounded-3xl border border-slate-200 bg-white p-7 shadow-sm"><div className="flex items-center justify-between gap-4"><span className="text-xs font-semibold uppercase tracking-[0.16em] text-[#168bb8]">0{index+1}</span><span className="rounded-full bg-[#f1fbf7] px-3 py-1 text-[11px] font-semibold uppercase tracking-[0.12em] text-[#287a59]">In development</span></div><h2 className="mt-6 text-2xl font-semibold text-[#102C5C]">{title}</h2><p className="mt-2 font-medium text-slate-700">{subtitle}</p><p className="mt-4 text-sm leading-7 text-slate-600">{body}</p><p className="mt-5 border-t border-slate-100 pt-4 text-xs leading-6 text-slate-500">{status}</p></article>)}</div></div></section>

    <section className="bg-[#102C5C] py-20 text-white"><div className="container-shell grid gap-10 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#65c7e8]">What a pilot involves</p><h2 className="mt-3 text-4xl font-semibold text-white">The first step is a production conversation.</h2></div><div><p className="text-lg leading-8 text-slate-200">A pilot has to be defined around the production setting, responsibilities, measurements and intended learning. Crabionics is not publishing logistics that have not been confirmed.</p><div className="mt-8 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-white/15 bg-white/5 p-5"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#9bd8eb]">To be defined</p><p className="mt-3 text-sm leading-7 text-slate-200">Site context, equipment responsibilities, duration, stages and partner outputs.</p></div><div className="rounded-2xl border border-white/15 bg-white/5 p-5"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#9bd8eb]">To discuss</p><p className="mt-3 text-sm leading-7 text-slate-200">Whether the production context is suitable for a controlled pilot conversation.</p></div></div><Link href="/contact" className="mt-8 inline-flex rounded-full bg-white px-6 py-3 text-sm font-semibold text-[#102C5C]">Discuss a mud-crab pilot</Link></div></div></section>

    <section className="py-20"><div className="container-shell flex flex-col justify-between gap-6 md:flex-row md:items-center"><div><h2 className="text-3xl font-semibold text-[#102C5C]">Need the technical architecture first?</h2><p className="mt-3 text-slate-600">See how the physical and operating layers connect.</p></div><Link href="/system" className="rounded-full border border-slate-300 px-6 py-3 text-sm font-semibold text-[#102C5C]">How the system works</Link></div></section></div>;
}
