import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "For Producers", description: "Production jobs, operating context and pilot questions for mud-crab producers considering Crabionics." };

const jobs = [
  ["01", "Set up the production environment", "Habitat", "Create a defined setting around the crab so handling, observation and operating conversations start from the same physical context.", "In development: the production setting and supporting infrastructure are being connected."],
  ["02", "Know what is happening around the unit", "CrabSense", "Connect environmental and operating observations to a specific production unit instead of treating readings as isolated numbers.", "In development: sensing scope is defined with each validation activity."],
  ["03", "Act close to the production work", "CrabPod", "Support flow, flushing and other local interventions where the operating decision is made.", "In development: hardware and deployment responsibilities are defined with each pilot partner."],
  ["04", "Keep a useful operating record", "AquaOS", "Connect conditions, actions and outcomes so the team can review what changed and what to examine next.", "In development: the software is being developed alongside the production work."],
];

export default function ProducersPage() {
  return <div className="bg-white text-slate-900"><section className="relative overflow-hidden bg-[#f5f8fb] py-20 lg:py-28"><div className="container-shell grid items-center gap-12 lg:grid-cols-[1.05fr_0.95fr]"><div><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#168bb8]">For mud-crab producers</p><h1 className="mt-4 text-5xl font-semibold tracking-[-0.04em] text-[#102C5C] sm:text-6xl">Start with the production job, not the technology label.</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-slate-600">Crabionics is building around the practical work of mud-crab production: defining the habitat, seeing conditions, supporting intervention, keeping records and deciding what to learn next.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/contact" className="rounded-full bg-[#102C5C] px-6 py-3 text-sm font-semibold text-white">Discuss a mud-crab pilot</Link><Link href="/system" className="rounded-full border border-slate-300 bg-white px-6 py-3 text-sm font-semibold text-[#102C5C]">See the system</Link></div></div><div className="relative hidden min-h-[360px] lg:block"><div className="absolute inset-y-0 left-1/2 w-px bg-[#102C5C]/15"></div><div className="absolute left-10 top-4 w-64 border border-[#102C5C] bg-white p-5 shadow-[12px_12px_0_#a8dfed]"><span className="text-xs font-semibold uppercase tracking-[0.16em] text-[#168bb8]">01</span><p className="mt-3 text-xl font-semibold text-[#102C5C]">Set up the production environment</p></div><div className="absolute right-0 top-32 w-64 border border-[#102C5C] bg-white p-5 shadow-[12px_12px_0_#dcecf0]"><span className="text-xs font-semibold uppercase tracking-[0.16em] text-[#168bb8]">02</span><p className="mt-3 text-xl font-semibold text-[#102C5C]">Know what is happening around the unit</p></div><div className="absolute bottom-0 left-20 w-64 border border-[#102C5C] bg-[#102C5C] p-5 text-white shadow-[12px_12px_0_#168bb8]"><span className="text-xs font-semibold uppercase tracking-[0.16em] text-[#9bd8eb]">03 → 04</span><p className="mt-3 text-xl font-semibold">Act, record and learn</p></div></div></div></section>

    <section className="py-16 lg:py-20"><div className="container-shell"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#168bb8]">Production jobs</p><h2 className="mt-3 text-4xl font-semibold tracking-[-0.035em] text-[#102C5C] sm:text-5xl">Four questions the operating team needs to keep connected.</h2><p className="mt-5 text-lg leading-8 text-slate-600">The system is being developed around these jobs. It is not a promise that every job is already solved.</p></div><div className="mt-12 grid gap-5 md:grid-cols-2">{jobs.map(([number,title,layer,body,status])=><article key={title} className="rounded-none border border-slate-200 border-l-4 border-l-[#168bb8] bg-white p-7 shadow-[0_18px_50px_rgba(16,44,92,0.07)] transition hover:-translate-y-1 hover:border-[#8bcfe4] hover:shadow-[0_24px_60px_rgba(16,44,92,0.12)]"><div className="flex items-center justify-between gap-4"><span className="text-xs font-semibold uppercase tracking-[0.16em] text-[#168bb8]">{number}</span><span className="rounded-full bg-[#f1fbf7] px-3 py-1 text-[11px] font-semibold uppercase tracking-[0.12em] text-[#287a59]">{layer}</span></div><h2 className="mt-6 text-2xl font-semibold text-[#102C5C]">{title}</h2><p className="mt-4 text-sm leading-7 text-slate-600">{body}</p><p className="mt-5 border-t border-slate-100 pt-4 text-xs leading-6 text-slate-500">{status}</p></article>)}</div></div></section>

    <section className="bg-[#102C5C] py-16 text-white lg:py-20"><div className="container-shell grid gap-8 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#65c7e8]">What a pilot involves</p><h2 className="mt-3 text-4xl font-semibold text-white">A defined production question and a shared operating plan.</h2></div><div><p className="text-lg leading-8 text-slate-200">A useful pilot conversation starts with the setting, the production question, the responsibilities on each side and the measurement that would inform the next step.</p><div className="mt-7 grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-white/15 bg-white/5 p-5"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#9bd8eb]">Partner brings</p><p className="mt-3 text-sm leading-7 text-slate-200">Site or production context, operating knowledge, equipment information and the people responsible for day-to-day work.</p></div><div className="rounded-2xl border border-white/15 bg-white/5 p-5"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#9bd8eb]">Together we define</p><p className="mt-3 text-sm leading-7 text-slate-200">What Crabionics supplies, what is measured, how responsibilities are shared and what learning would justify the next step.</p></div></div><Link href="/contact" className="mt-8 inline-flex rounded-full bg-white px-6 py-3 text-sm font-semibold text-[#102C5C]">Discuss a mud-crab pilot</Link></div></div></section>

    <section className="py-14"><div className="container-shell flex flex-col justify-between gap-6 md:flex-row md:items-center"><div><h2 className="text-3xl font-semibold text-[#102C5C]">Need the technical detail first?</h2><p className="mt-3 text-slate-600">See how habitat, observations, decisions, intervention and learning fit together.</p></div><Link href="/system" className="rounded-full border border-slate-300 px-6 py-3 text-sm font-semibold text-[#102C5C]">How the system works</Link></div></section></div>;
}
