import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";

export const metadata: Metadata = { title: "Company", description: "The field experience, engineering work and institutional relationships behind Crabionics." };

const people: Array<[string, string, string, string]> = [["Sameer Kumar Dalai", "Founder / company lead", "/team/sameer-kumar-dalai.jpg", "Field aquaculture, systems architecture and company execution."], ["M Abhishek", "Technology / AquaOS", "/team/m-abhishek.jpg", "Technology systems and the AquaOS operating layer."]];
const institutions = [["KIIT-TBI", "Technology incubation", "/logos/kiit-tbi.png"], ["BIRAC / IHMS", "Funded R&D relationship", "/logos/birac-big.png"], ["DPIIT Deep Tech", "Startup / deep-tech recognition", "/logos/dpiit-startup-india.png"]];

export default function CompanyPage() {
  return <div className="bg-white text-slate-900"><section className="bg-[#f5f8fb] py-24 lg:py-32"><div className="container-shell max-w-5xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#168bb8]">Company</p><h1 className="mt-4 text-5xl font-semibold tracking-[-0.04em] text-[#102C5C] sm:text-6xl">Built from the production problem outward.</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-slate-600">Crabionics brings field experience, engineering integration and operating software together around the practical difficulty of making mud-crab production more controlled and repeatable.</p></div></section>

    <section className="py-20 lg:py-24"><div className="container-shell"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#168bb8]">Origin</p><h2 className="mt-3 text-4xl font-semibold text-[#102C5C] sm:text-5xl">The company starts with field and R&amp;D experience, not software alone.</h2><p className="mt-5 text-lg leading-8 text-slate-600">Crabionics exists to connect the physical production environment, the biological problem and the operating decisions around them. Relevant Odisha and Andhra Pradesh field work, including Ninjacrab 2022, is treated as R&amp;D and operational history—not as proof of current commercial validation.</p></div><div className="mt-12 grid gap-5 md:grid-cols-2">{people.map(([name,role,photo,bio])=><article key={name} className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="relative h-64 bg-slate-100"><Image src={photo} alt={name} fill sizes="(max-width: 768px) 100vw, 50vw" className="object-cover" /></div><div className="p-6"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#168bb8]">{role}</p><h3 className="mt-2 text-xl font-semibold text-[#102C5C]">{name}</h3><p className="mt-3 text-sm leading-7 text-slate-600">{bio}</p></div></article>)}</div></div></section>

    <section className="border-y border-slate-200 bg-[#f8fafc] py-20"><div className="container-shell"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#168bb8]">Capability being established</p><h2 className="mt-3 text-3xl font-semibold text-[#102C5C] sm:text-4xl">Scientific validation capability is being established alongside the build.</h2><p className="mt-4 text-slate-600">The public company story should not invent a scientific lead or imply that biological validation is complete. The validation programme is designed to make that capability and evidence explicit over time.</p></div><div className="mt-9 grid gap-4 sm:grid-cols-3">{institutions.map(([name,caption,logo])=><div key={name} className="flex min-h-[150px] flex-col justify-between rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="relative h-12 w-full"><Image src={logo} alt={name} fill sizes="220px" className="object-contain object-left" /></div><div><p className="font-semibold text-[#102C5C]">{name}</p><p className="mt-1 text-xs leading-5 text-slate-500">{caption}</p></div></div>)}</div></div></section>

    <section className="bg-[#102C5C] py-20 text-white"><div className="container-shell flex flex-col justify-between gap-7 md:flex-row md:items-center"><div><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#65c7e8]">Company stage</p><h2 className="mt-3 text-3xl font-semibold text-white sm:text-4xl">Technology integration → controlled validation → preparation for repeatability.</h2></div><Link href="/validation" className="inline-flex shrink-0 rounded-full bg-white px-6 py-3 text-sm font-semibold text-[#102C5C]">See validation</Link></div></section></div>;
}
