import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";

export const metadata: Metadata = { title: "How the System Works", description: "How Crabionics connects habitat, observations, operating decisions, local intervention and learning for mud-crab production." };

const layers = [
  ["01", "Habitat", "Make the production setting more defined", "Problem addressed: uncontrolled variation in the physical environment and handling context.", "Operator receives: a production unit that can be described, observed and discussed consistently.", "Status: the production setting and supporting infrastructure are being connected; site requirements are defined with each production context.", "/photos/isolation-box.jpg"],
  ["02", "CrabSense", "See conditions around a production unit", "Problem addressed: observations that are disconnected from the animal, unit or operating event they describe.", "Operator receives: environmental and operating observations linked to a defined production context.", "Status: environmental sensing is being connected to the production setting; the relevant scope is defined for each validation activity.", "/photos/sensor-node.jpg"],
  ["03", "CrabPod", "Support an intervention close to the work", "Problem addressed: the gap between seeing a condition and being able to act on the local water or habitat environment.", "Operator receives: local hardware intended to support flow, flushing and other interventions.", "Status: local hardware is being connected to the production setting; deployment responsibilities are defined with each pilot partner.", "/photos/ras-plumbing.jpg"],
  ["04", "AquaOS", "Keep decisions and outcomes connected", "Problem addressed: operating actions and production outcomes that are difficult to trace back to conditions.", "Operator receives: records and workflows connecting conditions, actions and outcomes.", "Status: software in development alongside the physical production work.", "/aquaos-diagram.png"],
];

export default function SystemPage() {
  return <div className="bg-white text-slate-900"><section className="bg-[#102C5C] py-24 text-white lg:py-32"><div className="container-shell max-w-5xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#65c7e8]">How the system works</p><h1 className="mt-4 text-5xl font-semibold tracking-[-0.04em] text-white sm:text-6xl">A production system explained through the work it supports.</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-slate-200">Crabionics is connecting the physical setting, observations, operating decisions, local intervention and learning around mud-crab production. Each part has a different job; no single layer is presented as a completed commercial outcome.</p></div></section>

    <section className="py-20 lg:py-28"><div className="container-shell"><div className="rounded-3xl border border-slate-200 bg-[#f8fafc] p-7 sm:p-10"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#168bb8]">The operating loop</p><div className="mt-6 grid gap-3 text-center text-sm font-semibold text-[#102C5C] sm:grid-cols-9 sm:items-center"><span>Mud crab</span><span className="text-[#168bb8]">↓</span><span>Habitat</span><span className="text-[#168bb8]">↓</span><span>Observation</span><span className="text-[#168bb8]">↓</span><span>AquaOS / decision</span><span className="text-[#168bb8]">↓</span><span>CrabPod / intervention → operator → outcome → learning</span></div><p className="mt-7 border-t border-slate-200 pt-6 text-sm leading-7 text-slate-600">This is the intended operating logic: understand the setting, observe what is happening, decide what matters, support a local intervention, record the result and learn from the next cycle.</p></div><div className="mt-14 grid gap-6 md:grid-cols-2">{layers.map(([number,title,subtitle,problem,output,status,image])=><article key={title} className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="relative h-56 bg-slate-100"><Image src={image} alt={title} fill sizes="(max-width: 768px) 100vw, 50vw" className="object-cover" /></div><div className="p-7"><div className="flex items-center justify-between gap-4"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#168bb8]">{number}</p><p className="text-xs font-semibold uppercase tracking-[0.12em] text-slate-400">{title}</p></div><h2 className="mt-4 text-2xl font-semibold text-[#102C5C]">{subtitle}</h2><p className="mt-4 text-sm leading-7 text-slate-600"><strong className="font-semibold text-slate-800">{problem}</strong></p><p className="mt-3 text-sm leading-7 text-slate-600">{output}</p><p className="mt-5 border-t border-slate-100 pt-4 text-xs leading-6 text-slate-500">{status}</p></div></article>)}</div></div></section>

    <section className="border-y border-slate-200 bg-[#f8fafc] py-20"><div className="container-shell"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#168bb8]">What the system requires</p><h2 className="mt-3 text-3xl font-semibold text-[#102C5C] sm:text-4xl">The system works best when the production context is understood.</h2><p className="mt-4 text-slate-600">A site or pilot conversation needs to establish the production setting, equipment responsibilities, operating routines, relevant observations and the question the work is meant to answer.</p></div><div className="mt-10 grid gap-4 md:grid-cols-3"><div className="rounded-2xl border border-slate-200 bg-white p-6"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#168bb8]">Inputs</p><h3 className="mt-3 text-xl font-semibold text-[#102C5C]">Production context</h3><p className="mt-3 text-sm leading-7 text-slate-600">Setting, animals, water conditions, equipment and operating responsibilities.</p></div><div className="rounded-2xl border border-slate-200 bg-white p-6"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#168bb8]">Work</p><h3 className="mt-3 text-xl font-semibold text-[#102C5C]">Defined question</h3><p className="mt-3 text-sm leading-7 text-slate-600">A practical system, biological or commercial question with a defined measurement plan.</p></div><div className="rounded-2xl border border-slate-200 bg-white p-6"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#168bb8]">Learning</p><h3 className="mt-3 text-xl font-semibold text-[#102C5C]">Evidence for the next step</h3><p className="mt-3 text-sm leading-7 text-slate-600">A record of what was observed, what changed and what still needs to be tested.</p></div></div></div></section>

    <section className="py-20"><div className="container-shell flex flex-col justify-between gap-6 md:flex-row md:items-center"><div><h2 className="text-3xl font-semibold text-[#102C5C]">Want to understand the producer side?</h2><p className="mt-3 text-slate-600">See the operating jobs and the practical shape of a pilot conversation.</p></div><div className="flex flex-wrap gap-3"><Link href="/producers" className="rounded-full bg-[#102C5C] px-6 py-3 text-sm font-semibold text-white">For producers</Link><Link href="/contact" className="rounded-full border border-slate-300 px-6 py-3 text-sm font-semibold text-[#102C5C]">Discuss a question</Link></div></div></section></div>;
}
