import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";

export const metadata: Metadata = { title: "How the System Works", description: "How Crabionics connects habitat, sensing, edge control and operating software for mud-crab production." };

const layers = [
  ["01", "Habitat", "The physical production environment around the crab.", "Designed to make individual production conditions and handling more structured.", "/photos/isolation-box.jpg"],
  ["02", "CrabSense", "Environmental and operating observations.", "Designed to connect conditions to a defined production context.", "/photos/sensor-node.jpg"],
  ["03", "CrabPod", "Local edge control.", "Hardware intended to support flow, flush and other operational interventions.", "/photos/ras-plumbing.jpg"],
  ["04", "AquaOS", "Records, workflows and decision support.", "Being developed to connect conditions, actions and outcomes for the operator.", "/aquaos-diagram.png"],
];

export default function SystemPage() {
  return <div className="bg-white text-slate-900"><section className="bg-[#102C5C] py-24 text-white lg:py-32"><div className="container-shell max-w-5xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#65c7e8]">System</p><h1 className="mt-4 text-5xl font-semibold tracking-[-0.04em] text-white sm:text-6xl">A production architecture built around the crab.</h1><p className="mt-7 max-w-3xl text-lg leading-8 text-slate-200">Habitat, sensing, edge control and operating software are being integrated as one system. The objective is to make production conditions and operating decisions more observable, manageable and repeatable.</p></div></section>

    <section className="py-20 lg:py-28"><div className="container-shell"><div className="rounded-3xl border border-slate-200 bg-[#f8fafc] p-7 sm:p-10"><div className="grid gap-5 text-center text-sm font-semibold text-[#102C5C] sm:grid-cols-9 sm:items-center"><span>Mud crab</span><span className="text-[#168bb8]">↓</span><span>Habitat</span><span className="text-[#168bb8]">↓</span><span>CrabSense</span><span className="text-[#168bb8]">↓</span><span>AquaOS / decision</span><span className="text-[#168bb8]">↓</span><span>CrabPod / intervention → operator → outcome → learning</span></div><p className="mt-7 border-t border-slate-200 pt-6 text-center text-sm leading-7 text-slate-600">The intended loop connects the animal, physical environment, observations, decision support, local intervention, operator workflow and production learning. It is an architecture under integration and validation, not a claim of autonomous farming.</p></div><div className="mt-14 grid gap-6 md:grid-cols-2">{layers.map(([number,title,subtitle,body,image])=><article key={title} className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div className="relative h-56 bg-slate-100"><Image src={image} alt={title} fill sizes="(max-width: 768px) 100vw, 50vw" className="object-cover" /></div><div className="p-7"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#168bb8]">{number}</p><h2 className="mt-3 text-2xl font-semibold text-[#102C5C]">{title}</h2><p className="mt-2 font-medium text-slate-700">{subtitle}</p><p className="mt-4 text-sm leading-7 text-slate-600">{body}</p></div></article>)}</div></div></section>

    <section className="border-y border-slate-200 bg-[#f8fafc] py-20"><div className="container-shell"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-[#168bb8]">Public boundary</p><h2 className="mt-3 text-3xl font-semibold text-[#102C5C] sm:text-4xl">Engineering integration is not the same as biological or commercial validation.</h2></div><div className="mt-10 grid gap-4 md:grid-cols-3"><div className="rounded-2xl border border-[#ecd78e] bg-[#fffdf4] p-6"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#745a0a]">Engineering / integration proof</p><p className="mt-4 text-sm leading-7 text-slate-700">Shows that the physical, sensing, control and software elements can be integrated as intended.</p></div><div className="rounded-2xl border border-[#a8dfed] bg-[#effafd] p-6"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#176d85]">Biological validation</p><p className="mt-4 text-sm leading-7 text-slate-700">Requires separate evidence about biological outcomes in defined production settings.</p></div><div className="rounded-2xl border border-[#efc5c5] bg-[#fff7f7] p-6"><p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#8c3030]">Commercial validation</p><p className="mt-4 text-sm leading-7 text-slate-700">Requires separate evidence that producers and downstream partners can adopt the model.</p></div></div><p className="mt-8 rounded-2xl bg-[#102C5C] px-6 py-5 text-sm font-medium leading-7 text-white">BIRAC/IHMS milestone completion demonstrates engineering integration. It does not by itself demonstrate biological, economic or commercial outcomes. Those are validated separately, at later stages, with their own evidence.</p></div></section>

    <section className="py-20"><div className="container-shell flex flex-col justify-between gap-6 md:flex-row md:items-center"><div><h2 className="text-3xl font-semibold text-[#102C5C]">Want to understand the operator side?</h2><p className="mt-3 text-slate-600">See how the architecture is intended to translate into production jobs.</p></div><div className="flex flex-wrap gap-3"><Link href="/producers" className="rounded-full bg-[#102C5C] px-6 py-3 text-sm font-semibold text-white">For producers</Link><Link href="/aquaos" className="rounded-full border border-slate-300 px-6 py-3 text-sm font-semibold text-[#102C5C]">AquaOS</Link></div></div></section></div>;
}
