import Link from "next/link";

import GlassCard from "@/app/components/ui/GlassCard";
import SectionHeading from "@/app/components/ui/SectionHeading";
import SectionWrapper from "@/app/components/ui/SectionWrapper";

const architecture = [
  {
    title: "Physical Infrastructure",
    description:
      "Vertical RAS systems, modular isolation units, water circulation infrastructure, and production hardware.",
  },

  {
    title: "Sensor Layer",
    description:
      "Environmental telemetry including dissolved oxygen, salinity, pH, ammonia, temperature, and operational conditions.",
  },

  {
    title: "Telemetry Layer",
    description:
      "Continuous synchronization of biological, environmental, and infrastructure signals into operational datasets.",
  },

  {
    title: "Biological Intelligence",
    description:
      "Molting inference, behavioral analysis, stress detection, and survival optimization systems.",
  },

  {
    title: "Operational Logic",
    description:
      "Infrastructure response systems coordinating flushing, aeration, interventions, and production workflows.",
  },

  {
    title: "Distributed Learning",
    description:
      "Cross-cycle and cross-farm operational learning through the Crabionics Intelligence Network.",
  },
];

const systems = [
  {
    title: "Molting Intelligence",
    description:
      "Predictive estimation of high-risk biological windows for intervention timing and survival optimization.",
  },

  {
    title: "Risk Stabilization",
    description:
      "Detection of operational instability and environmental anomalies before production failure occurs.",
  },

  {
    title: "Crab Carbon Index (CCI)",
    description:
      "Production-linked sustainability metrics integrating biological operations with carbon accountability systems.",
  },
];

export default function TechnologyPage() {
  return (
    <main className="relative overflow-hidden">

      {/* HERO */}
      <section className="relative overflow-hidden border-b border-white/10">

        {/* GLOW */}
        <div className="absolute left-[-10%] top-[-20%] h-[420px] w-[420px] rounded-full bg-cyan-400/10 blur-3xl" />

        <div className="container-shell relative z-10 py-28 lg:py-36">

          <div className="max-w-5xl">

            {/* EYEBROW */}
            <div className="inline-flex rounded-full border border-cyan-400/20 bg-cyan-400/10 px-4 py-2 text-xs uppercase tracking-[0.22em] text-cyan-200">
              Technology Architecture
            </div>

            {/* TITLE */}
            <h1 className="mt-8 max-w-4xl">
              Biological Intelligence Infrastructure for Precision Aquaculture
            </h1>

            {/* TEXT */}
            <p className="mt-8 max-w-3xl text-lg">
              Crabionics integrates telemetry systems, biological
              intelligence, modular RAS infrastructure, and operational
              orchestration into a closed-loop production architecture.
            </p>
          </div>
        </div>
      </section>

      {/* STACK */}
      <SectionWrapper className="section-divider">

        <SectionHeading
          eyebrow="Infrastructure Stack"
          title="Closed-loop Operational Intelligence"
          subtitle="The Crabionics technology stack combines environmental telemetry, biological inference systems, and infrastructure orchestration into one operational ecosystem."
          align="center"
        />

        <div className="mt-20 grid gap-6 md:grid-cols-2 xl:grid-cols-3">

          {architecture.map((item) => (
            <GlassCard
              key={item.title}
              className="relative overflow-hidden p-8"
            >

              {/* GLOW */}
              <div className="absolute right-[-20%] top-[-20%] h-[160px] w-[160px] rounded-full bg-cyan-400/10 blur-3xl" />

              <div className="relative z-10">

                <div className="h-3 w-3 rounded-full bg-cyan-300" />

                <h3 className="mt-6">
                  {item.title}
                </h3>

                <p className="mt-5">
                  {item.description}
                </p>
              </div>
            </GlassCard>
          ))}
        </div>
      </SectionWrapper>

      {/* FLOW */}
      <SectionWrapper className="section-divider overflow-hidden">

        <SectionHeading
          eyebrow="Technology Flow"
          title="Sensor → Intelligence → Infrastructure Response"
          subtitle="Operational intelligence is generated by continuously linking telemetry signals with biological outcomes and production actions."
          align="center"
        />

        <div className="mx-auto mt-20 max-w-6xl">

          <div className="grid gap-6 lg:grid-cols-5">

            {[
              "Environmental Signals",
              "Telemetry Aggregation",
              "Biological Inference",
              "Operational Decisions",
              "Infrastructure Response",
            ].map((item, index) => (
              <GlassCard
                key={item}
                className="relative p-8 text-center"
              >

                {/* CONNECTOR */}
                {index !== 4 && (
                  <div className="absolute right-[-18px] top-1/2 hidden h-[2px] w-9 -translate-y-1/2 bg-cyan-400/20 lg:block" />
                )}

                <div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full border border-cyan-400/20 bg-cyan-400/10 text-sm font-semibold text-cyan-200">
                  0{index + 1}
                </div>

                <p className="mt-6 text-sm font-medium text-white">
                  {item}
                </p>
              </GlassCard>
            ))}
          </div>
        </div>
      </SectionWrapper>

      {/* CORE SYSTEMS */}
      <SectionWrapper className="section-divider">

        <SectionHeading
          eyebrow="Core Intelligence Systems"
          title="Biological and Operational Intelligence Layers"
          subtitle="Crabionics technology systems are designed to improve predictability, operational stability, and production consistency."
          align="center"
        />

        <div className="mx-auto mt-20 grid max-w-6xl gap-6 lg:grid-cols-3">

          {systems.map((item) => (
            <GlassCard
              key={item.title}
              className="p-8"
            >

              <div className="h-3 w-3 rounded-full bg-cyan-300" />

              <h3 className="mt-6">
                {item.title}
              </h3>

              <p className="mt-5">
                {item.description}
              </p>
            </GlassCard>
          ))}
        </div>
      </SectionWrapper>

      {/* LOWER PANEL */}
      <SectionWrapper>

        <div className="glass-card overflow-hidden p-10 lg:p-14">

          <div className="grid items-center gap-10 lg:grid-cols-[1fr_auto]">

            {/* LEFT */}
            <div>

              <p className="text-sm uppercase tracking-[0.18em] text-cyan-200">
                Precision Infrastructure
              </p>

              <h2 className="mt-5 max-w-3xl">
                Integrating Infrastructure, Intelligence, and Biological Operations
              </h2>

              <p className="mt-6 max-w-2xl text-lg">
                Explore the operational platform and biological orchestration systems powering the Crabionics ecosystem.
              </p>
            </div>

            {/* RIGHT */}
            <div className="flex flex-col gap-4 sm:flex-row lg:flex-col">

              <Link
                href="/aquaos"
                className="primary-button"
              >
                Explore AquaOS
              </Link>

              <Link
                href="/platform"
                className="secondary-button"
              >
                View Infrastructure
              </Link>
            </div>
          </div>
        </div>

      </SectionWrapper>

    </main>
  );
}